// A RemoteConfig builder for widget tests that need a config to PUMP rather
// than one to unit-test parsing against — that half is already covered by
// test/config/remote_config_test.dart's own `_body()` helper, which goes
// through parseRemoteConfig itself rather than constructing a RemoteConfig
// by hand.
//
// Every leaf is overridable and defaults to defaultRemoteConfig's own value,
// so a call site names only what it cares about. Introduced once several
// widget test files needed the same ~45-line constructor call (the "rule of
// three" this package's own code-simplification discipline uses) — existing
// per-file fixture builders (remote_config_client_test.dart's
// `withOverrides`, chat_widget_cubit_test.dart's `copyWithAccent`) are left
// as they are rather than retrofitted, since that would be an unrelated
// refactor of files outside this change's scope.

import 'package:dhaam_chat_flutter/dhaam_chat_flutter.dart';

RemoteConfig testRemoteConfig({
  bool enabled = true,
  String? accent,
  String? title,
  WidgetTheme? theme,
  WidgetPosition? position,
  double? offsetX,
  double? offsetY,
  LauncherStyle? launcher,
  String? launcherLabel,
  LauncherIcon launcherIcon = const LauncherIcon(),
  LauncherShadow launcherShadow = const LauncherShadow(),
  WidgetDesign? design,
  HeaderAppearance header = const HeaderAppearance(),
  String? logoUrl,
  String? subtitle,
  AvatarMode? avatarMode,
  String? avatarInitials,
  bool? showBranding,
  String? brandingText,
  String? brandingUrl,
  ThreadAppearance thread = const ThreadAppearance(),
  double? cornerRadius,
  String? fontFamily,
  String? greeting,
  double greetingDelaySec = 0,
  AutoOpen autoOpen = AutoOpen.never,
  double autoOpenDelaySec = 12,
  bool typingIndicator = true,
  bool sound = false,
  bool transcriptEmail = false,
  bool consentRequired = false,
  String? consentText,
  String? supportEmail,
  List<String> handoffKeywords = const <String>[],
  bool reportIssue = false,
  bool preChatEnabled = false,
  List<PreChatField> preChatFields = const <PreChatField>[],
  List<CommonQuestion> commonQuestions = const <CommonQuestion>[],
  List<ConversationTopic> conversationTopics = const <ConversationTopic>[],
  CsatStyle csatStyle = CsatStyle.stars,
  OfflineMode offlineMode = OfflineMode.showMessage,
  String? offlineMessage,
  bool fileUploads = true,
  bool? isOpenNow,
  List<PublishedFlow> flows = const <PublishedFlow>[],
  String? botDisplayName,
  int publishedVersion = 0,
}) {
  return RemoteConfig(
    enabled: enabled,
    accent: accent,
    title: title,
    theme: theme,
    position: position,
    offsetX: offsetX,
    offsetY: offsetY,
    launcher: launcher,
    launcherLabel: launcherLabel,
    launcherIcon: launcherIcon,
    launcherShadow: launcherShadow,
    design: design,
    header: header,
    logoUrl: logoUrl,
    subtitle: subtitle,
    avatarMode: avatarMode,
    avatarInitials: avatarInitials,
    showBranding: showBranding,
    brandingText: brandingText,
    brandingUrl: brandingUrl,
    thread: thread,
    cornerRadius: cornerRadius,
    fontFamily: fontFamily,
    greeting: greeting,
    greetingDelaySec: greetingDelaySec,
    autoOpen: autoOpen,
    autoOpenDelaySec: autoOpenDelaySec,
    typingIndicator: typingIndicator,
    sound: sound,
    transcriptEmail: transcriptEmail,
    consentRequired: consentRequired,
    consentText: consentText,
    supportEmail: supportEmail,
    handoffKeywords: handoffKeywords,
    reportIssue: reportIssue,
    preChatEnabled: preChatEnabled,
    preChatFields: preChatFields,
    commonQuestions: commonQuestions,
    conversationTopics: conversationTopics,
    csatStyle: csatStyle,
    offlineMode: offlineMode,
    offlineMessage: offlineMessage,
    fileUploads: fileUploads,
    isOpenNow: isOpenNow,
    flows: flows,
    botDisplayName: botDisplayName,
    publishedVersion: publishedVersion,
  );
}
