"""Code generated by clients/scripts/emit_base_path.py from openapi/chat-api.yaml. DO NOT EDIT."""

BASE_PATH = "/chat-services/api/v1"
"""Path every route on chat-service is mounted under, taken from the spec's
`servers` block. openapi-python-client does not bake it into the generated
client -- ``Client`` takes ``base_url`` -- so joining it is on the caller.
Use :func:`resolve_base_url` rather than concatenating by hand.
"""


def resolve_base_url(api_url: str) -> str:
    """Turn a chat-service origin into the ``base_url`` ``Client`` expects.

        client = AuthenticatedClient(
            base_url=resolve_base_url("https://chat.example.com"), token=...
        )

    A trailing slash on the origin is tolerated. A path segment on the origin
    is not stripped: ``apiUrl`` is documented as origin-only, and silently
    discarding a path a caller deliberately supplied would hide their mistake
    rather than surface it.
    """
    return api_url.rstrip("/") + BASE_PATH
