// Code generated by clients/scripts/emit_base_path.py from openapi/chat-api.yaml. DO NOT EDIT.

package chatapi

import "strings"

// BasePath is the path every route on chat-service is mounted under, taken
// from the spec's `servers` block. ogen does not bake it into the generated
// client -- NewClient takes a full server URL -- so joining it is on the
// caller. Use ResolveBaseURL rather than concatenating by hand.
const BasePath = "/chat-services/api/v1"

// ResolveBaseURL turns a chat-service origin (scheme + host, the value a
// consumer configures as apiUrl) into the server URL NewClient expects.
//
//	c, err := chatapi.NewClient(chatapi.ResolveBaseURL("https://chat.example.com"), sec)
//
// A trailing slash on the origin is tolerated. A path segment on the origin
// is not stripped: apiUrl is documented as origin-only, and silently
// discarding a path a caller deliberately supplied would hide their mistake
// rather than surface it.
func ResolveBaseURL(apiURL string) string {
	return strings.TrimRight(apiURL, "/") + BasePath
}
