// Code generated by ogen, DO NOT EDIT.

package chatapi

import (
	"context"
	"io"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CloseSession invokes closeSession operation.
	//
	// Transitions `status` to `CLOSED`. Backs the core method `client.closeSession(): Promise<void>` (PRD
	// §6.2) — there is no WebSocket frame type for this action in the T1 catalog, so it is a REST-only
	// operation in v2, same as v1.
	//
	// Idempotency: naturally idempotent. Calling this on a session that is already `CLOSED` returns `200`
	// with its current state, not an error — repeats are always safe with no `Idempotency-Key` needed.
	//
	// POST /sessions/{sessionId}/close
	CloseSession(ctx context.Context, request OptCloseSessionRequest, params CloseSessionParams) (CloseSessionRes, error)
	// CreateSession invokes createSession operation.
	//
	// Starts a new session, defaulting to `mode: BOT` and `status: OPEN` (PRD §12.5's observed
	// lifecycle). The caller's identity comes entirely from the validated `accessToken` — the request
	// body carries only optional client-side context, never customer identity fields, which fixes v1's
	// pattern of re-sending `customerId`/`customerName`/ `customerEmail` in the body even though the same
	// values were already embedded in the auth token.
	//
	// Open Question (not resolved by the PRD): PRD §12.3 documents that in v1, explicit REST session
	// creation is a client-orchestrated recovery path — used only when the socket's `connection.ack`
	// resolves to an already-`CLOSED` session — and PRD §8.3 explicitly leaves open whether v2 keeps
	// this client-side responsibility or moves it server-side inside `connection.ack` itself. This
	// endpoint is included because backend (non-WebSocket) SDKs need an explicit, REST-only way to start a
	// session regardless of how that question is resolved for the browser client; whether
	// `@dhaam-ccrm/core` ever calls it directly is exactly the open question above, not something this
	// document can settle.
	//
	// Idempotency: supports `Idempotency-Key`. Without it, retrying after a timeout may create two
	// sessions; with it, a replayed request within the key's 24h window returns the original session
	// unchanged.
	//
	// POST /sessions
	CreateSession(ctx context.Context, request OptCreateSessionRequest, params CreateSessionParams) (CreateSessionRes, error)
	// GetSessionFull invokes getSessionFull operation.
	//
	// Generalizes v1's `GET /sessions/{id}/full` (PRD §12.9, §12.10), which this spec confirms is the
	// origin of the read-watermark model: each entry in `participants[]` carries `lastReadAt`, and a
	// customer widget seeds its "seen" UI from the maximum `lastReadAt` across all `AGENT` participants
	// (defending against multi-agent sessions). This is a read-only view of that watermark — see this
	// document's top-level description for why there is no corresponding write endpoint here.
	//
	// `messages` is the most recent page (see `limit`), returned in ascending chronological order (oldest
	// first). Use `GET /sessions/{sessionId}/messages` with `before` to page further back.
	//
	// GET /sessions/{sessionId}/full
	GetSessionFull(ctx context.Context, params GetSessionFullParams) (GetSessionFullRes, error)
	// ListSessionMessages invokes listSessionMessages operation.
	//
	// Matches v1's proven pagination shape exactly (PRD §12.10, §6.3): opaque-id backward cursor
	// (`before`), a `limit`, and a `hasMore` boolean in the response. There is no forward cursor — live
	// messages arrive over the WebSocket (`message.new`, T1), not by polling this endpoint. Omit `before`
	// to fetch the most recent page (equivalent to the first page a scroll-up pagination UI would
	// request).
	//
	// Returned in ascending chronological order (oldest first) — the oldest message in the response is
	// the one immediately following the given `before` cursor, so a client can prepend the page to its
	// existing message list without re-sorting.
	//
	// GET /sessions/{sessionId}/messages
	ListSessionMessages(ctx context.Context, params ListSessionMessagesParams) (ListSessionMessagesRes, error)
	// ListSessions invokes listSessions operation.
	//
	// Hydrates `ChatState.pastSessions` (PRD §6.4), which the PRD specifies as state but never gave a
	// data source — this endpoint closes that gap.
	//
	// Replaces v1's `GET /chat/sessions/customer?tenantId=&customerId=` (`src/context.tsx:923`). That
	// shape is not carried forward: taking `customerId` as a query parameter means the endpoint trusts the
	// caller to declare whose sessions to return, so any customer could enumerate another's history by
	// changing one parameter. Here both tenant and customer identity are derived from the validated
	// `accessToken` and publishable key, and are not accepted as inputs.
	//
	// Ordered most-recent-first. Includes closed sessions — a customer reopening an earlier conversation
	// (PRD §12.5) needs to see them.
	//
	// GET /sessions
	ListSessions(ctx context.Context, params ListSessionsParams) (ListSessionsRes, error)
	// MintToken invokes mintToken operation.
	//
	// Called by the customer's own backend using their `dhsk_live_...` / `dhsk_test_...` secret key —
	// never by a browser (PRD §10.3). The customer's frontend calls their own backend endpoint (commonly
	// one they name `/token` or similar), which in turn calls this endpoint and relays only the resulting
	// `accessToken` to the frontend, which supplies it to the SDK via `getToken()` (PRD §6.1, §10.4).
	//
	// Idempotency: N/A — minting has no persisted side effect to de-duplicate. Each call mints a fresh,
	// independent token; retrying after a timeout is always safe.
	//
	// Open Question (PRD §18 Q6, unresolved): whether this endpoint should also absorb v1's separate,
	// hardcoded external identity-mapping call (`mapCustomer()` →
	// `https://docs-dev.dhaamai.com/customers/map`, PRD §12.6) so that v2 clients make one
	// identity-related network call instead of two. This spec models the contract as it stands today
	// (claims in, token out) and does not invent an absorbed identity-mapping shape pending that decision.
	//
	// POST /tokens
	MintToken(ctx context.Context, request *MintTokenRequest) (MintTokenRes, error)
	// ReopenSession invokes reopenSession operation.
	//
	// Backs `client.reopenSession(sessionId): Promise<ChatSession>` (PRD §6.2). Deliberately bypasses the
	// AI bot and jumps directly to `status: WAITING_FOR_AGENT`, `mode: HUMAN` — the exact semantics PRD
	// §12.5 confirms for v1's `reopenSession()`. There is no WebSocket frame type for this action in the
	// T1 catalog, so it is REST-only, as in v1.
	//
	// Only a session in `CLOSED` status can be reopened. Reopening a session in any other status returns
	// `400 VALIDATION_FAILED` — this is a request-validity error given current state, not a
	// `SESSION_CLOSED` error (which means the opposite: the session is closed and an action requires it
	// not to be).
	//
	// Idempotency: supports `Idempotency-Key`, since reopening has a real side effect (bypassing the bot,
	// notifying agent routing) that should not be duplicated by a naive client retry.
	//
	// POST /sessions/{sessionId}/reopen
	ReopenSession(ctx context.Context, params ReopenSessionParams) (ReopenSessionRes, error)
	// UploadSessionAttachment invokes uploadSessionAttachment operation.
	//
	// Step 1 of the two-step flow PRD §6.3 and §12.10 generalize from v1: this endpoint uploads and
	// stores the file and returns its metadata only. It does not create a chat message. The caller (core's
	// `client.sendAttachment()`) must follow up by sending a WS `message.send` frame (T1) whose
	// `d.metadata.attachment` carries this response verbatim — exactly as v1's client emits
	// `chat.message.send` with `metadata.attachment` immediately after this REST call succeeds.
	//
	// `attachment` is the message model's one canonical location for attachment data (see
	// `Message.attachment`) — v1 read it from either `message.attachment` or
	// `message.metadata.attachment` interchangeably (`raw.attachment ?? raw.metadata?.attachment`), which
	// D4's "one canonical name per concept" rule closes for v2.
	//
	// The session is identified by the URL path, not a form field — v1 passed `chatSessionId`
	// redundantly inside the multipart body even though the REST call already had nowhere else to route
	// to; this is a deliberate cleanup, not a functional change.
	//
	// This endpoint models the proxied-upload flow v1 actually uses today (multipart straight to
	// chat-service). PRD §18 Open Question 7 — whether v2 keeps this proxied shape or moves to
	// direct-to-S3 presigned URLs minted via REST — is explicitly unresolved and owned by the backend
	// team. A presigned-URL design would replace this single multipart `POST` with a pair of calls (e.g.
	// `POST .../attachments/upload-url` returning a presigned PUT target, then a client-side `PUT`
	// straight to storage) and would change this response shape to include upload-target fields instead of
	// a final `url`. Do not implement against a presigned flow from this spec — it is not modeled here,
	// only flagged.
	//
	// Idempotency: supports `Idempotency-Key`. Without it, retrying a timed-out upload may store the file
	// twice.
	//
	// File size and MIME-type limits are enforced server-side; the exact ceiling is not fixed by the PRD
	// (tracked as an open question in the T2 handoff, not invented here). Violating either returns
	// `VALIDATION_FAILED` (`413` for size, `415` for an unsupported MIME type).
	//
	// POST /sessions/{sessionId}/attachments
	UploadSessionAttachment(ctx context.Context, request *UploadSessionAttachmentReq, params UploadSessionAttachmentParams) (UploadSessionAttachmentRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CloseSession invokes closeSession operation.
//
// Transitions `status` to `CLOSED`. Backs the core method `client.closeSession(): Promise<void>` (PRD
// §6.2) — there is no WebSocket frame type for this action in the T1 catalog, so it is a REST-only
// operation in v2, same as v1.
//
// Idempotency: naturally idempotent. Calling this on a session that is already `CLOSED` returns `200`
// with its current state, not an error — repeats are always safe with no `Idempotency-Key` needed.
//
// POST /sessions/{sessionId}/close
func (c *Client) CloseSession(ctx context.Context, request OptCloseSessionRequest, params CloseSessionParams) (CloseSessionRes, error) {
	res, err := c.sendCloseSession(ctx, request, params)
	return res, err
}

func (c *Client) sendCloseSession(ctx context.Context, request OptCloseSessionRequest, params CloseSessionParams) (res CloseSessionRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/sessions/"
	{
		// Encode "sessionId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "sessionId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.SessionID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/close"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCloseSessionRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, CloseSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}
		{

			switch err := c.securityPublishableKey(ctx, CloseSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"PublishableKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000011},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeCloseSessionResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateSession invokes createSession operation.
//
// Starts a new session, defaulting to `mode: BOT` and `status: OPEN` (PRD §12.5's observed
// lifecycle). The caller's identity comes entirely from the validated `accessToken` — the request
// body carries only optional client-side context, never customer identity fields, which fixes v1's
// pattern of re-sending `customerId`/`customerName`/ `customerEmail` in the body even though the same
// values were already embedded in the auth token.
//
// Open Question (not resolved by the PRD): PRD §12.3 documents that in v1, explicit REST session
// creation is a client-orchestrated recovery path — used only when the socket's `connection.ack`
// resolves to an already-`CLOSED` session — and PRD §8.3 explicitly leaves open whether v2 keeps
// this client-side responsibility or moves it server-side inside `connection.ack` itself. This
// endpoint is included because backend (non-WebSocket) SDKs need an explicit, REST-only way to start a
// session regardless of how that question is resolved for the browser client; whether
// `@dhaam-ccrm/core` ever calls it directly is exactly the open question above, not something this
// document can settle.
//
// Idempotency: supports `Idempotency-Key`. Without it, retrying after a timeout may create two
// sessions; with it, a replayed request within the key's 24h window returns the original session
// unchanged.
//
// POST /sessions
func (c *Client) CreateSession(ctx context.Context, request OptCreateSessionRequest, params CreateSessionParams) (CreateSessionRes, error) {
	res, err := c.sendCreateSession(ctx, request, params)
	return res, err
}

func (c *Client) sendCreateSession(ctx context.Context, request OptCreateSessionRequest, params CreateSessionParams) (res CreateSessionRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/sessions"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateSessionRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IdempotencyKey.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, CreateSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}
		{

			switch err := c.securityPublishableKey(ctx, CreateSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"PublishableKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000011},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeCreateSessionResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetSessionFull invokes getSessionFull operation.
//
// Generalizes v1's `GET /sessions/{id}/full` (PRD §12.9, §12.10), which this spec confirms is the
// origin of the read-watermark model: each entry in `participants[]` carries `lastReadAt`, and a
// customer widget seeds its "seen" UI from the maximum `lastReadAt` across all `AGENT` participants
// (defending against multi-agent sessions). This is a read-only view of that watermark — see this
// document's top-level description for why there is no corresponding write endpoint here.
//
// `messages` is the most recent page (see `limit`), returned in ascending chronological order (oldest
// first). Use `GET /sessions/{sessionId}/messages` with `before` to page further back.
//
// GET /sessions/{sessionId}/full
func (c *Client) GetSessionFull(ctx context.Context, params GetSessionFullParams) (GetSessionFullRes, error) {
	res, err := c.sendGetSessionFull(ctx, params)
	return res, err
}

func (c *Client) sendGetSessionFull(ctx context.Context, params GetSessionFullParams) (res GetSessionFullRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/sessions/"
	{
		// Encode "sessionId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "sessionId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.SessionID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/full"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, GetSessionFullOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}
		{

			switch err := c.securityPublishableKey(ctx, GetSessionFullOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"PublishableKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000011},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeGetSessionFullResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListSessionMessages invokes listSessionMessages operation.
//
// Matches v1's proven pagination shape exactly (PRD §12.10, §6.3): opaque-id backward cursor
// (`before`), a `limit`, and a `hasMore` boolean in the response. There is no forward cursor — live
// messages arrive over the WebSocket (`message.new`, T1), not by polling this endpoint. Omit `before`
// to fetch the most recent page (equivalent to the first page a scroll-up pagination UI would
// request).
//
// Returned in ascending chronological order (oldest first) — the oldest message in the response is
// the one immediately following the given `before` cursor, so a client can prepend the page to its
// existing message list without re-sorting.
//
// GET /sessions/{sessionId}/messages
func (c *Client) ListSessionMessages(ctx context.Context, params ListSessionMessagesParams) (ListSessionMessagesRes, error) {
	res, err := c.sendListSessionMessages(ctx, params)
	return res, err
}

func (c *Client) sendListSessionMessages(ctx context.Context, params ListSessionMessagesParams) (res ListSessionMessagesRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/sessions/"
	{
		// Encode "sessionId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "sessionId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.SessionID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/messages"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "before" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Before.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ListSessionMessagesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}
		{

			switch err := c.securityPublishableKey(ctx, ListSessionMessagesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"PublishableKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000011},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeListSessionMessagesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListSessions invokes listSessions operation.
//
// Hydrates `ChatState.pastSessions` (PRD §6.4), which the PRD specifies as state but never gave a
// data source — this endpoint closes that gap.
//
// Replaces v1's `GET /chat/sessions/customer?tenantId=&customerId=` (`src/context.tsx:923`). That
// shape is not carried forward: taking `customerId` as a query parameter means the endpoint trusts the
// caller to declare whose sessions to return, so any customer could enumerate another's history by
// changing one parameter. Here both tenant and customer identity are derived from the validated
// `accessToken` and publishable key, and are not accepted as inputs.
//
// Ordered most-recent-first. Includes closed sessions — a customer reopening an earlier conversation
// (PRD §12.5) needs to see them.
//
// GET /sessions
func (c *Client) ListSessions(ctx context.Context, params ListSessionsParams) (ListSessionsRes, error) {
	res, err := c.sendListSessions(ctx, params)
	return res, err
}

func (c *Client) sendListSessions(ctx context.Context, params ListSessionsParams) (res ListSessionsRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/sessions"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ListSessionsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}
		{

			switch err := c.securityPublishableKey(ctx, ListSessionsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"PublishableKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000011},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeListSessionsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// MintToken invokes mintToken operation.
//
// Called by the customer's own backend using their `dhsk_live_...` / `dhsk_test_...` secret key —
// never by a browser (PRD §10.3). The customer's frontend calls their own backend endpoint (commonly
// one they name `/token` or similar), which in turn calls this endpoint and relays only the resulting
// `accessToken` to the frontend, which supplies it to the SDK via `getToken()` (PRD §6.1, §10.4).
//
// Idempotency: N/A — minting has no persisted side effect to de-duplicate. Each call mints a fresh,
// independent token; retrying after a timeout is always safe.
//
// Open Question (PRD §18 Q6, unresolved): whether this endpoint should also absorb v1's separate,
// hardcoded external identity-mapping call (`mapCustomer()` →
// `https://docs-dev.dhaamai.com/customers/map`, PRD §12.6) so that v2 clients make one
// identity-related network call instead of two. This spec models the contract as it stands today
// (claims in, token out) and does not invent an absorbed identity-mapping shape pending that decision.
//
// POST /tokens
func (c *Client) MintToken(ctx context.Context, request *MintTokenRequest) (MintTokenRes, error) {
	res, err := c.sendMintToken(ctx, request)
	return res, err
}

func (c *Client) sendMintToken(ctx context.Context, request *MintTokenRequest) (res MintTokenRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/tokens"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeMintTokenRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securitySecretKey(ctx, MintTokenOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SecretKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeMintTokenResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReopenSession invokes reopenSession operation.
//
// Backs `client.reopenSession(sessionId): Promise<ChatSession>` (PRD §6.2). Deliberately bypasses the
// AI bot and jumps directly to `status: WAITING_FOR_AGENT`, `mode: HUMAN` — the exact semantics PRD
// §12.5 confirms for v1's `reopenSession()`. There is no WebSocket frame type for this action in the
// T1 catalog, so it is REST-only, as in v1.
//
// Only a session in `CLOSED` status can be reopened. Reopening a session in any other status returns
// `400 VALIDATION_FAILED` — this is a request-validity error given current state, not a
// `SESSION_CLOSED` error (which means the opposite: the session is closed and an action requires it
// not to be).
//
// Idempotency: supports `Idempotency-Key`, since reopening has a real side effect (bypassing the bot,
// notifying agent routing) that should not be duplicated by a naive client retry.
//
// POST /sessions/{sessionId}/reopen
func (c *Client) ReopenSession(ctx context.Context, params ReopenSessionParams) (ReopenSessionRes, error) {
	res, err := c.sendReopenSession(ctx, params)
	return res, err
}

func (c *Client) sendReopenSession(ctx context.Context, params ReopenSessionParams) (res ReopenSessionRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/sessions/"
	{
		// Encode "sessionId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "sessionId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.SessionID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/reopen"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IdempotencyKey.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, ReopenSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}
		{

			switch err := c.securityPublishableKey(ctx, ReopenSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"PublishableKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000011},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeReopenSessionResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UploadSessionAttachment invokes uploadSessionAttachment operation.
//
// Step 1 of the two-step flow PRD §6.3 and §12.10 generalize from v1: this endpoint uploads and
// stores the file and returns its metadata only. It does not create a chat message. The caller (core's
// `client.sendAttachment()`) must follow up by sending a WS `message.send` frame (T1) whose
// `d.metadata.attachment` carries this response verbatim — exactly as v1's client emits
// `chat.message.send` with `metadata.attachment` immediately after this REST call succeeds.
//
// `attachment` is the message model's one canonical location for attachment data (see
// `Message.attachment`) — v1 read it from either `message.attachment` or
// `message.metadata.attachment` interchangeably (`raw.attachment ?? raw.metadata?.attachment`), which
// D4's "one canonical name per concept" rule closes for v2.
//
// The session is identified by the URL path, not a form field — v1 passed `chatSessionId`
// redundantly inside the multipart body even though the REST call already had nowhere else to route
// to; this is a deliberate cleanup, not a functional change.
//
// This endpoint models the proxied-upload flow v1 actually uses today (multipart straight to
// chat-service). PRD §18 Open Question 7 — whether v2 keeps this proxied shape or moves to
// direct-to-S3 presigned URLs minted via REST — is explicitly unresolved and owned by the backend
// team. A presigned-URL design would replace this single multipart `POST` with a pair of calls (e.g.
// `POST .../attachments/upload-url` returning a presigned PUT target, then a client-side `PUT`
// straight to storage) and would change this response shape to include upload-target fields instead of
// a final `url`. Do not implement against a presigned flow from this spec — it is not modeled here,
// only flagged.
//
// Idempotency: supports `Idempotency-Key`. Without it, retrying a timed-out upload may store the file
// twice.
//
// File size and MIME-type limits are enforced server-side; the exact ceiling is not fixed by the PRD
// (tracked as an open question in the T2 handoff, not invented here). Violating either returns
// `VALIDATION_FAILED` (`413` for size, `415` for an unsupported MIME type).
//
// POST /sessions/{sessionId}/attachments
func (c *Client) UploadSessionAttachment(ctx context.Context, request *UploadSessionAttachmentReq, params UploadSessionAttachmentParams) (UploadSessionAttachmentRes, error) {
	res, err := c.sendUploadSessionAttachment(ctx, request, params)
	return res, err
}

func (c *Client) sendUploadSessionAttachment(ctx context.Context, request *UploadSessionAttachmentReq, params UploadSessionAttachmentParams) (res UploadSessionAttachmentRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/sessions/"
	{
		// Encode "sessionId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "sessionId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.SessionID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/attachments"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUploadSessionAttachmentRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	h := uri.NewHeaderEncoder(r.Header)
	{
		cfg := uri.HeaderParameterEncodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IdempotencyKey.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode header")
		}
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityAccessToken(ctx, UploadSessionAttachmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"AccessToken\"")
			}
		}
		{

			switch err := c.securityPublishableKey(ctx, UploadSessionAttachmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"PublishableKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000011},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeUploadSessionAttachmentResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
