// Code generated by ogen, DO NOT EDIT.

package chatapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CloseSessionOperation                  OperationName = "CloseSession"
	CreateSessionOperation                 OperationName = "CreateSession"
	GetSessionFullOperation                OperationName = "GetSessionFull"
	ListCartsForContactOperation           OperationName = "ListCartsForContact"
	ListContactCartsOperation              OperationName = "ListContactCarts"
	ListSessionMessagesOperation           OperationName = "ListSessionMessages"
	ListSessionsOperation                  OperationName = "ListSessions"
	MintTokenOperation                     OperationName = "MintToken"
	RecordCommerceEventOperation           OperationName = "RecordCommerceEvent"
	RecordCommerceEventForContactOperation OperationName = "RecordCommerceEventForContact"
	ReopenSessionOperation                 OperationName = "ReopenSession"
	UploadAttachmentOperation              OperationName = "UploadAttachment"
	WebhookMessageCreatedOperation         OperationName = "WebhookMessageCreated"
	WebhookSessionClosedOperation          OperationName = "WebhookSessionClosed"
	WebhookSessionUpdatedOperation         OperationName = "WebhookSessionUpdated"
	WebhookTicketLinkedOperation           OperationName = "WebhookTicketLinked"
)
