// Code generated by ogen, DO NOT EDIT.

package chatapi

// CloseSessionParams is parameters of closeSession operation.
type CloseSessionParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
}

// GetSessionFullParams is parameters of getSessionFull operation.
type GetSessionFullParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
	// Parameter name and bounds corrected — the real query parameter is `messageLimit`, not `limit`
	// (`fullSessionQuerySchema`, `chat.validator.ts:44-46`), capped at 200 with a default of 50.
	MessageLimit OptInt `json:",omitempty,omitzero"`
}

// ListCartsForContactParams is parameters of listCartsForContact operation.
type ListCartsForContactParams struct {
	// Opaque contact identifier (`Contact.id`). Do not parse or rely on its internal structure. A contact
	// in another tenant, or that never existed, is `404`, never `403` — see each operation's
	// description.
	ID string
}

// ListContactCartsParams is parameters of listContactCarts operation.
type ListContactCartsParams struct {
	// Lowercase only — `LIVE` or `1` are `400`, not silently accepted. This is the query-parameter form;
	// the equivalent response field (`ContactCartRow.status`) is the integer `ContactCartStatus` code, not
	// this string — see that schema's description for why the two intentionally differ.
	Status OptListContactCartsStatus `json:",omitempty,omitzero"`
	// Inclusive lower bound on `cartValue`.
	MinValue OptFloat64 `json:",omitempty,omitzero"`
	// Inclusive upper bound on `cartValue`.
	MaxValue OptFloat64 `json:",omitempty,omitzero"`
	// ISO-8601. Filters on the cart row's `updatedAt`.
	UpdatedAfter OptDateTime `json:",omitempty,omitzero"`
	// ISO-8601. Filters on the cart row's `updatedAt`.
	UpdatedBefore OptDateTime `json:",omitempty,omitzero"`
	Page          OptInt      `json:",omitempty,omitzero"`
	// Reject, not clamp — a request above the max is `400`, never silently truncated. Same bound as
	// `GET /contacts`.
	PageSize OptInt `json:",omitempty,omitzero"`
	// `<column>:<asc|desc>`. Only these two columns are sortable here.
	Sort OptListContactCartsSort `json:",omitempty,omitzero"`
}

// ListSessionMessagesParams is parameters of listSessionMessages operation.
type ListSessionMessagesParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
	// Opaque message id cursor. Returns the page of messages immediately preceding this message. Omit to
	// fetch the most recent page.
	Before OptString `json:",omitempty,omitzero"`
	// Default corrected — `listMessagesQuerySchema` (`chat.validator.ts:39-42`) defaults to 30, not the
	// generic 20 an earlier revision of this document applied here. The 100 ceiling was already correct.
	Limit OptInt `json:",omitempty,omitzero"`
}

// ListSessionsParams is parameters of listSessions operation.
type ListSessionsParams struct {
	// Maximum number of sessions to return. Default corrected to 5 (was 6) as of this revision —
	// `customerSessionsQuerySchema` (`chat.validator.ts:52-58`). BREAKING for anything hardcoding the old
	// default, but this operation has zero callers (see above), so there is no consumer to coordinate the
	// change with. The cap stays 20, unrelated to the default and unchanged.
	Limit OptInt `json:",omitempty,omitzero"`
}

// RecordCommerceEventForContactParams is parameters of recordCommerceEventForContact operation.
type RecordCommerceEventForContactParams struct {
	// Opaque contact identifier (`Contact.id`). Do not parse or rely on its internal structure. A contact
	// in another tenant, or that never existed, is `404`, never `403` — see each operation's
	// description.
	ID string
}

// ReopenSessionParams is parameters of reopenSession operation.
type ReopenSessionParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
}

// UploadAttachmentParams is parameters of uploadAttachment operation.
type UploadAttachmentParams struct {
	// Tenant verification hint, checked before the `tenantId` query parameter. Never authoritative — see
	// description above.
	XTenantID OptString `json:",omitempty,omitzero"`
	// Tenant verification hint, used only if `X-Tenant-ID` is absent. Never authoritative — see
	// description above.
	TenantID OptString `json:",omitempty,omitzero"`
	// The session this attachment belongs to. Optional at the HTTP layer (the route does not verify the
	// session exists or that the caller owns it) — the caller is expected to supply it so the value can
	// be echoed back into the follow-up `message.send` frame. See "Session identification" above for why
	// this must be a query parameter, not a multipart field.
	ChatSessionID OptString `json:",omitempty,omitzero"`
}

// WebhookMessageCreatedParams is parameters of webhookMessageCreated operation.
type WebhookMessageCreatedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhk_live_...` / `dhk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}

// WebhookSessionClosedParams is parameters of webhookSessionClosed operation.
type WebhookSessionClosedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhk_live_...` / `dhk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}

// WebhookSessionUpdatedParams is parameters of webhookSessionUpdated operation.
type WebhookSessionUpdatedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhk_live_...` / `dhk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}

// WebhookTicketLinkedParams is parameters of webhookTicketLinked operation.
type WebhookTicketLinkedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhk_live_...` / `dhk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}
