// Code generated by ogen, DO NOT EDIT.

package chatapi

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AccessToken provides accessToken security value.
	// Short-lived, scoped user JWT minted by `POST /tokens` and supplied to `@dhaam-ccrm/core` via
	// `getToken()` (PRD §6.1, §10.4). Required, together with `publishableKey`, on every
	// session/message/attachment endpoint.
	AccessToken(ctx context.Context, operationName OperationName) (AccessToken, error)
	// PublishableKey provides publishableKey security value.
	// Tenant-identifying key (`dhpk_live_...` / `dhpk_test_...`), safe to ship in a client bundle.
	// Identifies a tenant and grants nothing on its own (PRD §10.1) — always required together with
	// `accessToken`, never as a sole credential. The server rejects a request whose `X-Publishable-Key`
	// tenant does not match the `accessToken`'s tenant claim with `401 AUTH_INVALID` (PRD §10.2).
	PublishableKey(ctx context.Context, operationName OperationName) (PublishableKey, error)
	// SecretKey provides secretKey security value.
	// Tenant secret key. Valid only as the credential on `POST /tokens` (never on any endpoint a browser
	// calls) and, separately, as the HMAC-SHA256 signing key for webhook signature verification. Must
	// never leave the customer's backend (PRD §10.1, §14).
	SecretKey(ctx context.Context, operationName OperationName) (SecretKey, error)
}

// operationRolesAccessToken is a private map storing roles per operation.
var operationRolesAccessToken = map[string][]string{
	CloseSessionOperation:            []string{},
	CreateSessionOperation:           []string{},
	GetSessionFullOperation:          []string{},
	ListSessionMessagesOperation:     []string{},
	ListSessionsOperation:            []string{},
	ReopenSessionOperation:           []string{},
	UploadSessionAttachmentOperation: []string{},
}

// GetRolesForAccessToken returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAccessToken(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAccessToken(operation string) []string {
	roles, ok := operationRolesAccessToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesPublishableKey is a private map storing roles per operation.
var operationRolesPublishableKey = map[string][]string{
	CloseSessionOperation:            []string{},
	CreateSessionOperation:           []string{},
	GetSessionFullOperation:          []string{},
	ListSessionMessagesOperation:     []string{},
	ListSessionsOperation:            []string{},
	ReopenSessionOperation:           []string{},
	UploadSessionAttachmentOperation: []string{},
}

// GetRolesForPublishableKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForPublishableKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForPublishableKey(operation string) []string {
	roles, ok := operationRolesPublishableKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesSecretKey is a private map storing roles per operation.
var operationRolesSecretKey = map[string][]string{
	MintTokenOperation: []string{},
}

// GetRolesForSecretKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForSecretKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForSecretKey(operation string) []string {
	roles, ok := operationRolesSecretKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityAccessToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AccessToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AccessToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityPublishableKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.PublishableKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"PublishableKey\"")
	}
	req.Header.Set("X-Publishable-Key", t.APIKey)
	return nil
}
func (s *Client) securitySecretKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.SecretKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"SecretKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
