// Code generated by ogen, DO NOT EDIT.
package chatapi

type CloseSessionRes interface {
	closeSessionRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type GetSessionFullRes interface {
	getSessionFullRes()
}

type ListSessionMessagesRes interface {
	listSessionMessagesRes()
}

type ListSessionsRes interface {
	listSessionsRes()
}

type MintTokenRes interface {
	mintTokenRes()
}

type ReopenSessionRes interface {
	reopenSessionRes()
}

type UploadSessionAttachmentRes interface {
	uploadSessionAttachmentRes()
}
