// Code generated by ogen, DO NOT EDIT.

package chatapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CloseSessionOperation            OperationName = "CloseSession"
	CreateSessionOperation           OperationName = "CreateSession"
	GetSessionFullOperation          OperationName = "GetSessionFull"
	ListSessionMessagesOperation     OperationName = "ListSessionMessages"
	ListSessionsOperation            OperationName = "ListSessions"
	MintTokenOperation               OperationName = "MintToken"
	ReopenSessionOperation           OperationName = "ReopenSession"
	UploadSessionAttachmentOperation OperationName = "UploadSessionAttachment"
	WebhookMessageCreatedOperation   OperationName = "WebhookMessageCreated"
	WebhookSessionClosedOperation    OperationName = "WebhookSessionClosed"
	WebhookSessionUpdatedOperation   OperationName = "WebhookSessionUpdated"
	WebhookTicketLinkedOperation     OperationName = "WebhookTicketLinked"
)
