// Code generated by ogen, DO NOT EDIT.

package chatapi

// CloseSessionParams is parameters of closeSession operation.
type CloseSessionParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
}

// CreateSessionParams is parameters of createSession operation.
type CreateSessionParams struct {
	// Client-generated opaque token (UUID recommended). A replayed request with the same key within 24h
	// returns the original response instead of repeating the side effect.
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// GetSessionFullParams is parameters of getSessionFull operation.
type GetSessionFullParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
	// Maximum number of items to return.
	Limit OptInt `json:",omitempty,omitzero"`
}

// ListSessionMessagesParams is parameters of listSessionMessages operation.
type ListSessionMessagesParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
	// Opaque message id cursor. Returns the page of messages immediately preceding this message. Omit to
	// fetch the most recent page.
	Before OptString `json:",omitempty,omitzero"`
	// Maximum number of items to return.
	Limit OptInt `json:",omitempty,omitzero"`
}

// ListSessionsParams is parameters of listSessions operation.
type ListSessionsParams struct {
	// Maximum number of items to return.
	Limit OptInt `json:",omitempty,omitzero"`
}

// ReopenSessionParams is parameters of reopenSession operation.
type ReopenSessionParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
	// Client-generated opaque token (UUID recommended). A replayed request with the same key within 24h
	// returns the original response instead of repeating the side effect.
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// UploadSessionAttachmentParams is parameters of uploadSessionAttachment operation.
type UploadSessionAttachmentParams struct {
	// Opaque session identifier. Do not parse or rely on its internal structure.
	SessionID string
	// Client-generated opaque token (UUID recommended). A replayed request with the same key within 24h
	// returns the original response instead of repeating the side effect.
	IdempotencyKey OptString `json:",omitempty,omitzero"`
}

// WebhookMessageCreatedParams is parameters of webhookMessageCreated operation.
type WebhookMessageCreatedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhsk_live_...` / `dhsk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}

// WebhookSessionClosedParams is parameters of webhookSessionClosed operation.
type WebhookSessionClosedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhsk_live_...` / `dhsk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}

// WebhookSessionUpdatedParams is parameters of webhookSessionUpdated operation.
type WebhookSessionUpdatedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhsk_live_...` / `dhsk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}

// WebhookTicketLinkedParams is parameters of webhookTicketLinked operation.
type WebhookTicketLinkedParams struct {
	// `t=<unix-seconds>,v1=<hex-encoded HMAC-SHA256>`. The signed payload is `${t}.${rawRequestBody}`,
	// HMAC-SHA256'd with the tenant's secret key (`dhsk_live_...` / `dhsk_test_...`) as the key. Verify by
	// recomputing the HMAC over the raw, unparsed body and comparing with constant-time comparison; reject
	// if `t` is more than 5 minutes from the receiver's clock (replay protection). `@dhaam-ccrm/node`
	// (T16) implements this verification so consumers never hand-roll it.
	XChatSDKSignature string
	// Unique id for this delivery attempt's underlying event (same value as the body's `id`). Use for
	// de-duplication — retries of the same event reuse this id.
	XChatSDKWebhookID string
	// Same value as the body's `type`. Lets a receiver route without parsing the body first.
	XChatSDKEventType string
	// 1-indexed delivery attempt number. Retries use exponential backoff; receivers should treat delivery
	// as at-least-once and dedupe on `X-ChatSDK-Webhook-Id`.
	XChatSDKWebhookAttempt int
}
