// Code generated by ogen, DO NOT EDIT.

package chatapi

// setDefaults set default value of fields.
func (s *CloseSessionRequest) setDefaults() {
	{
		val := CloseReason("MANUAL")
		s.Reason.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WebhookSessionClosedEventData) setDefaults() {
	{
		val := CloseReason("MANUAL")
		s.CloseReason = val
	}
}
