// Code generated by ogen, DO NOT EDIT.
package chatapi

type CloseSessionRes interface {
	closeSessionRes()
}

type CreateSessionRes interface {
	createSessionRes()
}

type GetSessionFullRes interface {
	getSessionFullRes()
}

type ListCartsForContactRes interface {
	listCartsForContactRes()
}

type ListContactCartsRes interface {
	listContactCartsRes()
}

type ListSessionMessagesRes interface {
	listSessionMessagesRes()
}

type ListSessionsRes interface {
	listSessionsRes()
}

type MintTokenRes interface {
	mintTokenRes()
}

type RecordCommerceEventForContactRes interface {
	recordCommerceEventForContactRes()
}

type RecordCommerceEventRes interface {
	recordCommerceEventRes()
}

type ReopenSessionRes interface {
	reopenSessionRes()
}

type UploadAttachmentRes interface {
	uploadAttachmentRes()
}
