// Code generated by ogen, DO NOT EDIT.

package chatapi

import (
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

type AccessToken struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *AccessToken) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *AccessToken) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *AccessToken) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *AccessToken) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Attachment
type Attachment struct {
	URL      url.URL `json:"url"`
	FileName string  `json:"fileName"`
	MimeType string  `json:"mimeType"`
	// Size in bytes.
	Size      int       `json:"size"`
	MediaType MediaType `json:"mediaType"`
}

// GetURL returns the value of URL.
func (s *Attachment) GetURL() url.URL {
	return s.URL
}

// GetFileName returns the value of FileName.
func (s *Attachment) GetFileName() string {
	return s.FileName
}

// GetMimeType returns the value of MimeType.
func (s *Attachment) GetMimeType() string {
	return s.MimeType
}

// GetSize returns the value of Size.
func (s *Attachment) GetSize() int {
	return s.Size
}

// GetMediaType returns the value of MediaType.
func (s *Attachment) GetMediaType() MediaType {
	return s.MediaType
}

// SetURL sets the value of URL.
func (s *Attachment) SetURL(val url.URL) {
	s.URL = val
}

// SetFileName sets the value of FileName.
func (s *Attachment) SetFileName(val string) {
	s.FileName = val
}

// SetMimeType sets the value of MimeType.
func (s *Attachment) SetMimeType(val string) {
	s.MimeType = val
}

// SetSize sets the value of Size.
func (s *Attachment) SetSize(val int) {
	s.Size = val
}

// SetMediaType sets the value of MediaType.
func (s *Attachment) SetMediaType(val MediaType) {
	s.MediaType = val
}

func (*Attachment) uploadSessionAttachmentRes() {}

// BadRequestHeaders wraps Error with response headers.
type BadRequestHeaders struct {
	XRequestID OptString
	Response   Error
}

// GetXRequestID returns the value of XRequestID.
func (s *BadRequestHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *BadRequestHeaders) GetResponse() Error {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *BadRequestHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *BadRequestHeaders) SetResponse(val Error) {
	s.Response = val
}

func (*BadRequestHeaders) createSessionRes()           {}
func (*BadRequestHeaders) mintTokenRes()               {}
func (*BadRequestHeaders) reopenSessionRes()           {}
func (*BadRequestHeaders) uploadSessionAttachmentRes() {}

// Ref: #/components/schemas/ChatMessage
type ChatMessage struct {
	// Opaque message identifier. Under D1, this is the client-generated ULID for customer-sent messages
	// — it never changes after creation; there is no separate server-assigned id to swap in later.
	ID            string       `json:"id"`
	ChatSessionID string       `json:"chatSessionId"`
	SenderType    SenderType   `json:"senderType"`
	SenderID      OptNilString `json:"senderId"`
	SenderName    OptNilString `json:"senderName"`
	Content       string       `json:"content"`
	MessageType   MessageType  `json:"messageType"`
	// The one canonical timestamp field for this concept (D4) — v1 aliased this across four different
	// field names (`timestamp`/`createdAt`/`created_at`/`sentAt`) depending on endpoint and rollout era.
	CreatedAt time.Time `json:"createdAt"`
	// The one canonical location for attachment data (D4) — v1 read this from either
	// `message.attachment` or `message.metadata.attachment` interchangeably.
	Attachment       OptNilAttachment          `json:"attachment"`
	ReplyToMessageID OptNilString              `json:"replyToMessageId"`
	ReplyToMessage   OptNilMessageReplyPreview `json:"replyToMessage"`
	// Free-form additional context. Never used for attachment data — see `attachment`.
	Metadata OptChatMessageMetadata `json:"metadata"`
}

// GetID returns the value of ID.
func (s *ChatMessage) GetID() string {
	return s.ID
}

// GetChatSessionID returns the value of ChatSessionID.
func (s *ChatMessage) GetChatSessionID() string {
	return s.ChatSessionID
}

// GetSenderType returns the value of SenderType.
func (s *ChatMessage) GetSenderType() SenderType {
	return s.SenderType
}

// GetSenderID returns the value of SenderID.
func (s *ChatMessage) GetSenderID() OptNilString {
	return s.SenderID
}

// GetSenderName returns the value of SenderName.
func (s *ChatMessage) GetSenderName() OptNilString {
	return s.SenderName
}

// GetContent returns the value of Content.
func (s *ChatMessage) GetContent() string {
	return s.Content
}

// GetMessageType returns the value of MessageType.
func (s *ChatMessage) GetMessageType() MessageType {
	return s.MessageType
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ChatMessage) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetAttachment returns the value of Attachment.
func (s *ChatMessage) GetAttachment() OptNilAttachment {
	return s.Attachment
}

// GetReplyToMessageID returns the value of ReplyToMessageID.
func (s *ChatMessage) GetReplyToMessageID() OptNilString {
	return s.ReplyToMessageID
}

// GetReplyToMessage returns the value of ReplyToMessage.
func (s *ChatMessage) GetReplyToMessage() OptNilMessageReplyPreview {
	return s.ReplyToMessage
}

// GetMetadata returns the value of Metadata.
func (s *ChatMessage) GetMetadata() OptChatMessageMetadata {
	return s.Metadata
}

// SetID sets the value of ID.
func (s *ChatMessage) SetID(val string) {
	s.ID = val
}

// SetChatSessionID sets the value of ChatSessionID.
func (s *ChatMessage) SetChatSessionID(val string) {
	s.ChatSessionID = val
}

// SetSenderType sets the value of SenderType.
func (s *ChatMessage) SetSenderType(val SenderType) {
	s.SenderType = val
}

// SetSenderID sets the value of SenderID.
func (s *ChatMessage) SetSenderID(val OptNilString) {
	s.SenderID = val
}

// SetSenderName sets the value of SenderName.
func (s *ChatMessage) SetSenderName(val OptNilString) {
	s.SenderName = val
}

// SetContent sets the value of Content.
func (s *ChatMessage) SetContent(val string) {
	s.Content = val
}

// SetMessageType sets the value of MessageType.
func (s *ChatMessage) SetMessageType(val MessageType) {
	s.MessageType = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ChatMessage) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetAttachment sets the value of Attachment.
func (s *ChatMessage) SetAttachment(val OptNilAttachment) {
	s.Attachment = val
}

// SetReplyToMessageID sets the value of ReplyToMessageID.
func (s *ChatMessage) SetReplyToMessageID(val OptNilString) {
	s.ReplyToMessageID = val
}

// SetReplyToMessage sets the value of ReplyToMessage.
func (s *ChatMessage) SetReplyToMessage(val OptNilMessageReplyPreview) {
	s.ReplyToMessage = val
}

// SetMetadata sets the value of Metadata.
func (s *ChatMessage) SetMetadata(val OptChatMessageMetadata) {
	s.Metadata = val
}

// Free-form additional context. Never used for attachment data — see `attachment`.
type ChatMessageMetadata map[string]jx.Raw

func (s *ChatMessageMetadata) init() ChatMessageMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ChatMode
type ChatMode string

const (
	ChatModeBOT   ChatMode = "BOT"
	ChatModeHUMAN ChatMode = "HUMAN"
)

// AllValues returns all ChatMode values.
func (ChatMode) AllValues() []ChatMode {
	return []ChatMode{
		ChatModeBOT,
		ChatModeHUMAN,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatMode) MarshalText() ([]byte, error) {
	switch s {
	case ChatModeBOT:
		return []byte(s), nil
	case ChatModeHUMAN:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatMode) UnmarshalText(data []byte) error {
	switch ChatMode(data) {
	case ChatModeBOT:
		*s = ChatModeBOT
		return nil
	case ChatModeHUMAN:
		*s = ChatModeHUMAN
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatSession
type ChatSession struct {
	// Opaque session identifier.
	ID            string      `json:"id"`
	Status        ChatStatus  `json:"status"`
	Mode          ChatMode    `json:"mode"`
	CreatedAt     time.Time   `json:"createdAt"`
	ClosedAt      NilDateTime `json:"closedAt"`
	AssignedAgent NilProfile  `json:"assignedAgent"`
	Customer      NilProfile  `json:"customer"`
	Ticket        NilTicket   `json:"ticket"`
}

// GetID returns the value of ID.
func (s *ChatSession) GetID() string {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *ChatSession) GetStatus() ChatStatus {
	return s.Status
}

// GetMode returns the value of Mode.
func (s *ChatSession) GetMode() ChatMode {
	return s.Mode
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ChatSession) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetClosedAt returns the value of ClosedAt.
func (s *ChatSession) GetClosedAt() NilDateTime {
	return s.ClosedAt
}

// GetAssignedAgent returns the value of AssignedAgent.
func (s *ChatSession) GetAssignedAgent() NilProfile {
	return s.AssignedAgent
}

// GetCustomer returns the value of Customer.
func (s *ChatSession) GetCustomer() NilProfile {
	return s.Customer
}

// GetTicket returns the value of Ticket.
func (s *ChatSession) GetTicket() NilTicket {
	return s.Ticket
}

// SetID sets the value of ID.
func (s *ChatSession) SetID(val string) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *ChatSession) SetStatus(val ChatStatus) {
	s.Status = val
}

// SetMode sets the value of Mode.
func (s *ChatSession) SetMode(val ChatMode) {
	s.Mode = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ChatSession) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetClosedAt sets the value of ClosedAt.
func (s *ChatSession) SetClosedAt(val NilDateTime) {
	s.ClosedAt = val
}

// SetAssignedAgent sets the value of AssignedAgent.
func (s *ChatSession) SetAssignedAgent(val NilProfile) {
	s.AssignedAgent = val
}

// SetCustomer sets the value of Customer.
func (s *ChatSession) SetCustomer(val NilProfile) {
	s.Customer = val
}

// SetTicket sets the value of Ticket.
func (s *ChatSession) SetTicket(val NilTicket) {
	s.Ticket = val
}

func (*ChatSession) closeSessionRes()  {}
func (*ChatSession) reopenSessionRes() {}

// ChatSessionHeaders wraps ChatSession with response headers.
type ChatSessionHeaders struct {
	Location OptString
	Response ChatSession
}

// GetLocation returns the value of Location.
func (s *ChatSessionHeaders) GetLocation() OptString {
	return s.Location
}

// GetResponse returns the value of Response.
func (s *ChatSessionHeaders) GetResponse() ChatSession {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *ChatSessionHeaders) SetLocation(val OptString) {
	s.Location = val
}

// SetResponse sets the value of Response.
func (s *ChatSessionHeaders) SetResponse(val ChatSession) {
	s.Response = val
}

func (*ChatSessionHeaders) createSessionRes() {}

// Lightweight session projection for history lists. Deliberately smaller than `ChatSession` — a
// history panel renders a label, a timestamp, and an unread badge, and should not pay for participant
// or ticket payloads it will not draw.
// Ref: #/components/schemas/ChatSessionSummary
type ChatSessionSummary struct {
	// Opaque session identifier.
	ID        string      `json:"id"`
	Status    ChatStatus  `json:"status"`
	Mode      ChatMode    `json:"mode"`
	CreatedAt time.Time   `json:"createdAt"`
	ClosedAt  NilDateTime `json:"closedAt"`
	// Timestamp of the most recent message, or null if the session has none.
	LastMessageAt NilDateTime `json:"lastMessageAt"`
	// Truncated plain-text preview of the most recent message.
	LastMessagePreview OptString `json:"lastMessagePreview"`
	// Messages after this customer's read watermark (PRD §9.5).
	UnreadCount int `json:"unreadCount"`
}

// GetID returns the value of ID.
func (s *ChatSessionSummary) GetID() string {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *ChatSessionSummary) GetStatus() ChatStatus {
	return s.Status
}

// GetMode returns the value of Mode.
func (s *ChatSessionSummary) GetMode() ChatMode {
	return s.Mode
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ChatSessionSummary) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetClosedAt returns the value of ClosedAt.
func (s *ChatSessionSummary) GetClosedAt() NilDateTime {
	return s.ClosedAt
}

// GetLastMessageAt returns the value of LastMessageAt.
func (s *ChatSessionSummary) GetLastMessageAt() NilDateTime {
	return s.LastMessageAt
}

// GetLastMessagePreview returns the value of LastMessagePreview.
func (s *ChatSessionSummary) GetLastMessagePreview() OptString {
	return s.LastMessagePreview
}

// GetUnreadCount returns the value of UnreadCount.
func (s *ChatSessionSummary) GetUnreadCount() int {
	return s.UnreadCount
}

// SetID sets the value of ID.
func (s *ChatSessionSummary) SetID(val string) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *ChatSessionSummary) SetStatus(val ChatStatus) {
	s.Status = val
}

// SetMode sets the value of Mode.
func (s *ChatSessionSummary) SetMode(val ChatMode) {
	s.Mode = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ChatSessionSummary) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetClosedAt sets the value of ClosedAt.
func (s *ChatSessionSummary) SetClosedAt(val NilDateTime) {
	s.ClosedAt = val
}

// SetLastMessageAt sets the value of LastMessageAt.
func (s *ChatSessionSummary) SetLastMessageAt(val NilDateTime) {
	s.LastMessageAt = val
}

// SetLastMessagePreview sets the value of LastMessagePreview.
func (s *ChatSessionSummary) SetLastMessagePreview(val OptString) {
	s.LastMessagePreview = val
}

// SetUnreadCount sets the value of UnreadCount.
func (s *ChatSessionSummary) SetUnreadCount(val int) {
	s.UnreadCount = val
}

// The full six-value status set (PRD §12.1, D4) — v1's own type system modeled only four of these
// (`OPEN`/`WAITING_FOR_AGENT`/`ASSIGNED`/ `CLOSED`), silently collapsing `RESOLVED`/`ON_HOLD` traffic
// to `OPEN`.
// Ref: #/components/schemas/ChatStatus
type ChatStatus string

const (
	ChatStatusOPEN            ChatStatus = "OPEN"
	ChatStatusWAITINGFORAGENT ChatStatus = "WAITING_FOR_AGENT"
	ChatStatusASSIGNED        ChatStatus = "ASSIGNED"
	ChatStatusCLOSED          ChatStatus = "CLOSED"
	ChatStatusRESOLVED        ChatStatus = "RESOLVED"
	ChatStatusONHOLD          ChatStatus = "ON_HOLD"
)

// AllValues returns all ChatStatus values.
func (ChatStatus) AllValues() []ChatStatus {
	return []ChatStatus{
		ChatStatusOPEN,
		ChatStatusWAITINGFORAGENT,
		ChatStatusASSIGNED,
		ChatStatusCLOSED,
		ChatStatusRESOLVED,
		ChatStatusONHOLD,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatStatus) MarshalText() ([]byte, error) {
	switch s {
	case ChatStatusOPEN:
		return []byte(s), nil
	case ChatStatusWAITINGFORAGENT:
		return []byte(s), nil
	case ChatStatusASSIGNED:
		return []byte(s), nil
	case ChatStatusCLOSED:
		return []byte(s), nil
	case ChatStatusRESOLVED:
		return []byte(s), nil
	case ChatStatusONHOLD:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatStatus) UnmarshalText(data []byte) error {
	switch ChatStatus(data) {
	case ChatStatusOPEN:
		*s = ChatStatusOPEN
		return nil
	case ChatStatusWAITINGFORAGENT:
		*s = ChatStatusWAITINGFORAGENT
		return nil
	case ChatStatusASSIGNED:
		*s = ChatStatusASSIGNED
		return nil
	case ChatStatusCLOSED:
		*s = ChatStatusCLOSED
		return nil
	case ChatStatusRESOLVED:
		*s = ChatStatusRESOLVED
		return nil
	case ChatStatusONHOLD:
		*s = ChatStatusONHOLD
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// First-class enum for why a session entered CLOSED (PRD §12.5) — v1 only had this as a loose
// `string | null` code comment (`'SWITCHED' | 'MANUAL' | null`).
// Ref: #/components/schemas/CloseReason
type CloseReason string

const (
	CloseReasonMANUAL   CloseReason = "MANUAL"
	CloseReasonSWITCHED CloseReason = "SWITCHED"
)

// AllValues returns all CloseReason values.
func (CloseReason) AllValues() []CloseReason {
	return []CloseReason{
		CloseReasonMANUAL,
		CloseReasonSWITCHED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CloseReason) MarshalText() ([]byte, error) {
	switch s {
	case CloseReasonMANUAL:
		return []byte(s), nil
	case CloseReasonSWITCHED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CloseReason) UnmarshalText(data []byte) error {
	switch CloseReason(data) {
	case CloseReasonMANUAL:
		*s = CloseReasonMANUAL
		return nil
	case CloseReasonSWITCHED:
		*s = CloseReasonSWITCHED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CloseSessionRequest
type CloseSessionRequest struct {
	Reason OptCloseReason `json:"reason"`
}

// GetReason returns the value of Reason.
func (s *CloseSessionRequest) GetReason() OptCloseReason {
	return s.Reason
}

// SetReason sets the value of Reason.
func (s *CloseSessionRequest) SetReason(val OptCloseReason) {
	s.Reason = val
}

// ConflictHeaders wraps Error with response headers.
type ConflictHeaders struct {
	XRequestID OptString
	Response   Error
}

// GetXRequestID returns the value of XRequestID.
func (s *ConflictHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *ConflictHeaders) GetResponse() Error {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *ConflictHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *ConflictHeaders) SetResponse(val Error) {
	s.Response = val
}

func (*ConflictHeaders) uploadSessionAttachmentRes() {}

// Customer identity is derived entirely from the validated `accessToken` — this body never repeats
// it.
// Ref: #/components/schemas/CreateSessionRequest
type CreateSessionRequest struct {
	// Optional free-form client-side context (e.g. originating page URL, locale).
	Metadata OptCreateSessionRequestMetadata `json:"metadata"`
}

// GetMetadata returns the value of Metadata.
func (s *CreateSessionRequest) GetMetadata() OptCreateSessionRequestMetadata {
	return s.Metadata
}

// SetMetadata sets the value of Metadata.
func (s *CreateSessionRequest) SetMetadata(val OptCreateSessionRequestMetadata) {
	s.Metadata = val
}

// Optional free-form client-side context (e.g. originating page URL, locale).
type CreateSessionRequestMetadata map[string]jx.Raw

func (s *CreateSessionRequestMetadata) init() CreateSessionRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/Error
type Error struct {
	Error ErrorPayload `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() ErrorPayload {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val ErrorPayload) {
	s.Error = val
}

// Identical to the WS protocol's canonical `ErrorCode` (PRD §7.4) — one enum shared by both
// transports. Not every value can occur on every surface (e.g. `PROTOCOL_VERSION_UNSUPPORTED` is
// WS-only); see this document's top-level Error Taxonomy table for the REST-specific subset and HTTP
// status mapping.
// Ref: #/components/schemas/ErrorCode
type ErrorCode string

const (
	ErrorCodeAUTHINVALID                ErrorCode = "AUTH_INVALID"
	ErrorCodeAUTHEXPIRED                ErrorCode = "AUTH_EXPIRED"
	ErrorCodePROTOCOLVERSIONUNSUPPORTED ErrorCode = "PROTOCOL_VERSION_UNSUPPORTED"
	ErrorCodeRATELIMITED                ErrorCode = "RATE_LIMITED"
	ErrorCodeVALIDATIONFAILED           ErrorCode = "VALIDATION_FAILED"
	ErrorCodeSESSIONNOTFOUND            ErrorCode = "SESSION_NOT_FOUND"
	ErrorCodeSESSIONCLOSED              ErrorCode = "SESSION_CLOSED"
	ErrorCodeINTERNAL                   ErrorCode = "INTERNAL"
)

// AllValues returns all ErrorCode values.
func (ErrorCode) AllValues() []ErrorCode {
	return []ErrorCode{
		ErrorCodeAUTHINVALID,
		ErrorCodeAUTHEXPIRED,
		ErrorCodePROTOCOLVERSIONUNSUPPORTED,
		ErrorCodeRATELIMITED,
		ErrorCodeVALIDATIONFAILED,
		ErrorCodeSESSIONNOTFOUND,
		ErrorCodeSESSIONCLOSED,
		ErrorCodeINTERNAL,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorCodeAUTHINVALID:
		return []byte(s), nil
	case ErrorCodeAUTHEXPIRED:
		return []byte(s), nil
	case ErrorCodePROTOCOLVERSIONUNSUPPORTED:
		return []byte(s), nil
	case ErrorCodeRATELIMITED:
		return []byte(s), nil
	case ErrorCodeVALIDATIONFAILED:
		return []byte(s), nil
	case ErrorCodeSESSIONNOTFOUND:
		return []byte(s), nil
	case ErrorCodeSESSIONCLOSED:
		return []byte(s), nil
	case ErrorCodeINTERNAL:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorCode) UnmarshalText(data []byte) error {
	switch ErrorCode(data) {
	case ErrorCodeAUTHINVALID:
		*s = ErrorCodeAUTHINVALID
		return nil
	case ErrorCodeAUTHEXPIRED:
		*s = ErrorCodeAUTHEXPIRED
		return nil
	case ErrorCodePROTOCOLVERSIONUNSUPPORTED:
		*s = ErrorCodePROTOCOLVERSIONUNSUPPORTED
		return nil
	case ErrorCodeRATELIMITED:
		*s = ErrorCodeRATELIMITED
		return nil
	case ErrorCodeVALIDATIONFAILED:
		*s = ErrorCodeVALIDATIONFAILED
		return nil
	case ErrorCodeSESSIONNOTFOUND:
		*s = ErrorCodeSESSIONNOTFOUND
		return nil
	case ErrorCodeSESSIONCLOSED:
		*s = ErrorCodeSESSIONCLOSED
		return nil
	case ErrorCodeINTERNAL:
		*s = ErrorCodeINTERNAL
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Identical shape to the WS protocol's ErrorPayload (PRD §7.2).
// Ref: #/components/schemas/ErrorPayload
type ErrorPayload struct {
	Code ErrorCode `json:"code"`
	// Human-readable. Not for programmatic branching — branch on `code`.
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
	// Structured, error-specific context (e.g. which field failed validation).
	Details OptErrorPayloadDetails `json:"details"`
}

// GetCode returns the value of Code.
func (s *ErrorPayload) GetCode() ErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorPayload) GetMessage() string {
	return s.Message
}

// GetRetryable returns the value of Retryable.
func (s *ErrorPayload) GetRetryable() bool {
	return s.Retryable
}

// GetDetails returns the value of Details.
func (s *ErrorPayload) GetDetails() OptErrorPayloadDetails {
	return s.Details
}

// SetCode sets the value of Code.
func (s *ErrorPayload) SetCode(val ErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorPayload) SetMessage(val string) {
	s.Message = val
}

// SetRetryable sets the value of Retryable.
func (s *ErrorPayload) SetRetryable(val bool) {
	s.Retryable = val
}

// SetDetails sets the value of Details.
func (s *ErrorPayload) SetDetails(val OptErrorPayloadDetails) {
	s.Details = val
}

// Structured, error-specific context (e.g. which field failed validation).
type ErrorPayloadDetails map[string]jx.Raw

func (s *ErrorPayloadDetails) init() ErrorPayloadDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// InternalErrorHeaders wraps Error with response headers.
type InternalErrorHeaders struct {
	RetryAfter OptInt
	XRequestID OptString
	Response   Error
}

// GetRetryAfter returns the value of RetryAfter.
func (s *InternalErrorHeaders) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetXRequestID returns the value of XRequestID.
func (s *InternalErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *InternalErrorHeaders) GetResponse() Error {
	return s.Response
}

// SetRetryAfter sets the value of RetryAfter.
func (s *InternalErrorHeaders) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetXRequestID sets the value of XRequestID.
func (s *InternalErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorHeaders) SetResponse(val Error) {
	s.Response = val
}

func (*InternalErrorHeaders) closeSessionRes()            {}
func (*InternalErrorHeaders) createSessionRes()           {}
func (*InternalErrorHeaders) getSessionFullRes()          {}
func (*InternalErrorHeaders) listSessionMessagesRes()     {}
func (*InternalErrorHeaders) listSessionsRes()            {}
func (*InternalErrorHeaders) mintTokenRes()               {}
func (*InternalErrorHeaders) reopenSessionRes()           {}
func (*InternalErrorHeaders) uploadSessionAttachmentRes() {}

// Attachment category. Normalized to upper-snake-case for consistency with every other enum in this
// document (D4) — v1's wire value was lower-case-plural (`images`/`videos`/`audio`/`documents`);
// this is a deliberate v1→v2 casing fix, not a PRD-mandated rename, and should be reconciled with
// the backend team alongside the other D4 backend work (plan §2, B4).
// Ref: #/components/schemas/MediaType
type MediaType string

const (
	MediaTypeIMAGE    MediaType = "IMAGE"
	MediaTypeVIDEO    MediaType = "VIDEO"
	MediaTypeAUDIO    MediaType = "AUDIO"
	MediaTypeDOCUMENT MediaType = "DOCUMENT"
)

// AllValues returns all MediaType values.
func (MediaType) AllValues() []MediaType {
	return []MediaType{
		MediaTypeIMAGE,
		MediaTypeVIDEO,
		MediaTypeAUDIO,
		MediaTypeDOCUMENT,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MediaType) MarshalText() ([]byte, error) {
	switch s {
	case MediaTypeIMAGE:
		return []byte(s), nil
	case MediaTypeVIDEO:
		return []byte(s), nil
	case MediaTypeAUDIO:
		return []byte(s), nil
	case MediaTypeDOCUMENT:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MediaType) UnmarshalText(data []byte) error {
	switch MediaType(data) {
	case MediaTypeIMAGE:
		*s = MediaTypeIMAGE
		return nil
	case MediaTypeVIDEO:
		*s = MediaTypeVIDEO
		return nil
	case MediaTypeAUDIO:
		*s = MediaTypeAUDIO
		return nil
	case MediaTypeDOCUMENT:
		*s = MediaTypeDOCUMENT
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/MessagePage
type MessagePage struct {
	Messages []ChatMessage `json:"messages"`
	HasMore  bool          `json:"hasMore"`
}

// GetMessages returns the value of Messages.
func (s *MessagePage) GetMessages() []ChatMessage {
	return s.Messages
}

// GetHasMore returns the value of HasMore.
func (s *MessagePage) GetHasMore() bool {
	return s.HasMore
}

// SetMessages sets the value of Messages.
func (s *MessagePage) SetMessages(val []ChatMessage) {
	s.Messages = val
}

// SetHasMore sets the value of HasMore.
func (s *MessagePage) SetHasMore(val bool) {
	s.HasMore = val
}

func (*MessagePage) listSessionMessagesRes() {}

// Denormalized preview of the message being replied to.
// Ref: #/components/schemas/MessageReplyPreview
type MessageReplyPreview struct {
	ID          string         `json:"id"`
	Content     string         `json:"content"`
	SenderType  SenderType     `json:"senderType"`
	SenderID    OptNilString   `json:"senderId"`
	SenderName  OptNilString   `json:"senderName"`
	MessageType OptMessageType `json:"messageType"`
}

// GetID returns the value of ID.
func (s *MessageReplyPreview) GetID() string {
	return s.ID
}

// GetContent returns the value of Content.
func (s *MessageReplyPreview) GetContent() string {
	return s.Content
}

// GetSenderType returns the value of SenderType.
func (s *MessageReplyPreview) GetSenderType() SenderType {
	return s.SenderType
}

// GetSenderID returns the value of SenderID.
func (s *MessageReplyPreview) GetSenderID() OptNilString {
	return s.SenderID
}

// GetSenderName returns the value of SenderName.
func (s *MessageReplyPreview) GetSenderName() OptNilString {
	return s.SenderName
}

// GetMessageType returns the value of MessageType.
func (s *MessageReplyPreview) GetMessageType() OptMessageType {
	return s.MessageType
}

// SetID sets the value of ID.
func (s *MessageReplyPreview) SetID(val string) {
	s.ID = val
}

// SetContent sets the value of Content.
func (s *MessageReplyPreview) SetContent(val string) {
	s.Content = val
}

// SetSenderType sets the value of SenderType.
func (s *MessageReplyPreview) SetSenderType(val SenderType) {
	s.SenderType = val
}

// SetSenderID sets the value of SenderID.
func (s *MessageReplyPreview) SetSenderID(val OptNilString) {
	s.SenderID = val
}

// SetSenderName sets the value of SenderName.
func (s *MessageReplyPreview) SetSenderName(val OptNilString) {
	s.SenderName = val
}

// SetMessageType sets the value of MessageType.
func (s *MessageReplyPreview) SetMessageType(val OptMessageType) {
	s.MessageType = val
}

// Ref: #/components/schemas/MessageType
type MessageType string

const (
	MessageTypeTEXT   MessageType = "TEXT"
	MessageTypeSYSTEM MessageType = "SYSTEM"
	MessageTypeFILE   MessageType = "FILE"
	MessageTypeIMAGE  MessageType = "IMAGE"
	MessageTypeVIDEO  MessageType = "VIDEO"
	MessageTypeAUDIO  MessageType = "AUDIO"
)

// AllValues returns all MessageType values.
func (MessageType) AllValues() []MessageType {
	return []MessageType{
		MessageTypeTEXT,
		MessageTypeSYSTEM,
		MessageTypeFILE,
		MessageTypeIMAGE,
		MessageTypeVIDEO,
		MessageTypeAUDIO,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MessageType) MarshalText() ([]byte, error) {
	switch s {
	case MessageTypeTEXT:
		return []byte(s), nil
	case MessageTypeSYSTEM:
		return []byte(s), nil
	case MessageTypeFILE:
		return []byte(s), nil
	case MessageTypeIMAGE:
		return []byte(s), nil
	case MessageTypeVIDEO:
		return []byte(s), nil
	case MessageTypeAUDIO:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MessageType) UnmarshalText(data []byte) error {
	switch MessageType(data) {
	case MessageTypeTEXT:
		*s = MessageTypeTEXT
		return nil
	case MessageTypeSYSTEM:
		*s = MessageTypeSYSTEM
		return nil
	case MessageTypeFILE:
		*s = MessageTypeFILE
		return nil
	case MessageTypeIMAGE:
		*s = MessageTypeIMAGE
		return nil
	case MessageTypeVIDEO:
		*s = MessageTypeVIDEO
		return nil
	case MessageTypeAUDIO:
		*s = MessageTypeAUDIO
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/MintTokenRequest
type MintTokenRequest struct {
	// Stable identifier for the end user in the customer's own system. Becomes the token's `sub` claim and
	// the resulting session's customer identity.
	UserID          string    `json:"userId"`
	Name            OptString `json:"name"`
	Email           OptString `json:"email"`
	AdditionalProps MintTokenRequestAdditional
}

// GetUserID returns the value of UserID.
func (s *MintTokenRequest) GetUserID() string {
	return s.UserID
}

// GetName returns the value of Name.
func (s *MintTokenRequest) GetName() OptString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *MintTokenRequest) GetEmail() OptString {
	return s.Email
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *MintTokenRequest) GetAdditionalProps() MintTokenRequestAdditional {
	return s.AdditionalProps
}

// SetUserID sets the value of UserID.
func (s *MintTokenRequest) SetUserID(val string) {
	s.UserID = val
}

// SetName sets the value of Name.
func (s *MintTokenRequest) SetName(val OptString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *MintTokenRequest) SetEmail(val OptString) {
	s.Email = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *MintTokenRequest) SetAdditionalProps(val MintTokenRequestAdditional) {
	s.AdditionalProps = val
}

type MintTokenRequestAdditional map[string]jx.Raw

func (s *MintTokenRequestAdditional) init() MintTokenRequestAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/MintTokenResponse
type MintTokenResponse struct {
	// Short-lived JWT. Pass to the SDK via `getToken()` (PRD §6.1).
	AccessToken string `json:"accessToken"`
	// Token lifetime in seconds from the moment of minting.
	ExpiresIn int `json:"expiresIn"`
}

// GetAccessToken returns the value of AccessToken.
func (s *MintTokenResponse) GetAccessToken() string {
	return s.AccessToken
}

// GetExpiresIn returns the value of ExpiresIn.
func (s *MintTokenResponse) GetExpiresIn() int {
	return s.ExpiresIn
}

// SetAccessToken sets the value of AccessToken.
func (s *MintTokenResponse) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetExpiresIn sets the value of ExpiresIn.
func (s *MintTokenResponse) SetExpiresIn(val int) {
	s.ExpiresIn = val
}

func (*MintTokenResponse) mintTokenRes() {}

// NewNilDateTime returns new NilDateTime with value set to v.
func NewNilDateTime(v time.Time) NilDateTime {
	return NilDateTime{
		Value: v,
	}
}

// NilDateTime is nullable time.Time.
type NilDateTime struct {
	Value time.Time
	Null  bool
}

// SetTo sets value to v.
func (o *NilDateTime) SetTo(v time.Time) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilDateTime) SetToNull() {
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilProfile returns new NilProfile with value set to v.
func NewNilProfile(v Profile) NilProfile {
	return NilProfile{
		Value: v,
	}
}

// NilProfile is nullable Profile.
type NilProfile struct {
	Value Profile
	Null  bool
}

// SetTo sets value to v.
func (o *NilProfile) SetTo(v Profile) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilProfile) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilProfile) SetToNull() {
	o.Null = true
	var v Profile
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilProfile) Get() (v Profile, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilProfile) Or(d Profile) Profile {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilTicket returns new NilTicket with value set to v.
func NewNilTicket(v Ticket) NilTicket {
	return NilTicket{
		Value: v,
	}
}

// NilTicket is nullable Ticket.
type NilTicket struct {
	Value Ticket
	Null  bool
}

// SetTo sets value to v.
func (o *NilTicket) SetTo(v Ticket) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilTicket) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilTicket) SetToNull() {
	o.Null = true
	var v Ticket
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilTicket) Get() (v Ticket, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilTicket) Or(d Ticket) Ticket {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilURI returns new NilURI with value set to v.
func NewNilURI(v url.URL) NilURI {
	return NilURI{
		Value: v,
	}
}

// NilURI is nullable url.URL.
type NilURI struct {
	Value url.URL
	Null  bool
}

// SetTo sets value to v.
func (o *NilURI) SetTo(v url.URL) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilURI) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilURI) SetToNull() {
	o.Null = true
	var v url.URL
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilURI) Get() (v url.URL, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NotFoundHeaders wraps Error with response headers.
type NotFoundHeaders struct {
	XRequestID OptString
	Response   Error
}

// GetXRequestID returns the value of XRequestID.
func (s *NotFoundHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *NotFoundHeaders) GetResponse() Error {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *NotFoundHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *NotFoundHeaders) SetResponse(val Error) {
	s.Response = val
}

func (*NotFoundHeaders) closeSessionRes()            {}
func (*NotFoundHeaders) getSessionFullRes()          {}
func (*NotFoundHeaders) listSessionMessagesRes()     {}
func (*NotFoundHeaders) reopenSessionRes()           {}
func (*NotFoundHeaders) uploadSessionAttachmentRes() {}

// NewOptChatMessageMetadata returns new OptChatMessageMetadata with value set to v.
func NewOptChatMessageMetadata(v ChatMessageMetadata) OptChatMessageMetadata {
	return OptChatMessageMetadata{
		Value: v,
		Set:   true,
	}
}

// OptChatMessageMetadata is optional ChatMessageMetadata.
type OptChatMessageMetadata struct {
	Value ChatMessageMetadata
	Set   bool
}

// IsSet returns true if OptChatMessageMetadata was set.
func (o OptChatMessageMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChatMessageMetadata) Reset() {
	var v ChatMessageMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChatMessageMetadata) SetTo(v ChatMessageMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChatMessageMetadata) Get() (v ChatMessageMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChatMessageMetadata) Or(d ChatMessageMetadata) ChatMessageMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCloseReason returns new OptCloseReason with value set to v.
func NewOptCloseReason(v CloseReason) OptCloseReason {
	return OptCloseReason{
		Value: v,
		Set:   true,
	}
}

// OptCloseReason is optional CloseReason.
type OptCloseReason struct {
	Value CloseReason
	Set   bool
}

// IsSet returns true if OptCloseReason was set.
func (o OptCloseReason) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCloseReason) Reset() {
	var v CloseReason
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCloseReason) SetTo(v CloseReason) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCloseReason) Get() (v CloseReason, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCloseReason) Or(d CloseReason) CloseReason {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCloseSessionRequest returns new OptCloseSessionRequest with value set to v.
func NewOptCloseSessionRequest(v CloseSessionRequest) OptCloseSessionRequest {
	return OptCloseSessionRequest{
		Value: v,
		Set:   true,
	}
}

// OptCloseSessionRequest is optional CloseSessionRequest.
type OptCloseSessionRequest struct {
	Value CloseSessionRequest
	Set   bool
}

// IsSet returns true if OptCloseSessionRequest was set.
func (o OptCloseSessionRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCloseSessionRequest) Reset() {
	var v CloseSessionRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCloseSessionRequest) SetTo(v CloseSessionRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCloseSessionRequest) Get() (v CloseSessionRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCloseSessionRequest) Or(d CloseSessionRequest) CloseSessionRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateSessionRequest returns new OptCreateSessionRequest with value set to v.
func NewOptCreateSessionRequest(v CreateSessionRequest) OptCreateSessionRequest {
	return OptCreateSessionRequest{
		Value: v,
		Set:   true,
	}
}

// OptCreateSessionRequest is optional CreateSessionRequest.
type OptCreateSessionRequest struct {
	Value CreateSessionRequest
	Set   bool
}

// IsSet returns true if OptCreateSessionRequest was set.
func (o OptCreateSessionRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSessionRequest) Reset() {
	var v CreateSessionRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSessionRequest) SetTo(v CreateSessionRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSessionRequest) Get() (v CreateSessionRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSessionRequest) Or(d CreateSessionRequest) CreateSessionRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateSessionRequestMetadata returns new OptCreateSessionRequestMetadata with value set to v.
func NewOptCreateSessionRequestMetadata(v CreateSessionRequestMetadata) OptCreateSessionRequestMetadata {
	return OptCreateSessionRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptCreateSessionRequestMetadata is optional CreateSessionRequestMetadata.
type OptCreateSessionRequestMetadata struct {
	Value CreateSessionRequestMetadata
	Set   bool
}

// IsSet returns true if OptCreateSessionRequestMetadata was set.
func (o OptCreateSessionRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSessionRequestMetadata) Reset() {
	var v CreateSessionRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSessionRequestMetadata) SetTo(v CreateSessionRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSessionRequestMetadata) Get() (v CreateSessionRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSessionRequestMetadata) Or(d CreateSessionRequestMetadata) CreateSessionRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorPayloadDetails returns new OptErrorPayloadDetails with value set to v.
func NewOptErrorPayloadDetails(v ErrorPayloadDetails) OptErrorPayloadDetails {
	return OptErrorPayloadDetails{
		Value: v,
		Set:   true,
	}
}

// OptErrorPayloadDetails is optional ErrorPayloadDetails.
type OptErrorPayloadDetails struct {
	Value ErrorPayloadDetails
	Set   bool
}

// IsSet returns true if OptErrorPayloadDetails was set.
func (o OptErrorPayloadDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorPayloadDetails) Reset() {
	var v ErrorPayloadDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorPayloadDetails) SetTo(v ErrorPayloadDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorPayloadDetails) Get() (v ErrorPayloadDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorPayloadDetails) Or(d ErrorPayloadDetails) ErrorPayloadDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMessageType returns new OptMessageType with value set to v.
func NewOptMessageType(v MessageType) OptMessageType {
	return OptMessageType{
		Value: v,
		Set:   true,
	}
}

// OptMessageType is optional MessageType.
type OptMessageType struct {
	Value MessageType
	Set   bool
}

// IsSet returns true if OptMessageType was set.
func (o OptMessageType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMessageType) Reset() {
	var v MessageType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMessageType) SetTo(v MessageType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMessageType) Get() (v MessageType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMessageType) Or(d MessageType) MessageType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilAttachment returns new OptNilAttachment with value set to v.
func NewOptNilAttachment(v Attachment) OptNilAttachment {
	return OptNilAttachment{
		Value: v,
		Set:   true,
	}
}

// OptNilAttachment is optional nullable Attachment.
type OptNilAttachment struct {
	Value Attachment
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilAttachment was set.
func (o OptNilAttachment) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilAttachment) Reset() {
	var v Attachment
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilAttachment) SetTo(v Attachment) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilAttachment) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilAttachment) SetToNull() {
	o.Set = true
	o.Null = true
	var v Attachment
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilAttachment) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilAttachment) Get() (v Attachment, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilAttachment) Or(d Attachment) Attachment {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilMessageReplyPreview returns new OptNilMessageReplyPreview with value set to v.
func NewOptNilMessageReplyPreview(v MessageReplyPreview) OptNilMessageReplyPreview {
	return OptNilMessageReplyPreview{
		Value: v,
		Set:   true,
	}
}

// OptNilMessageReplyPreview is optional nullable MessageReplyPreview.
type OptNilMessageReplyPreview struct {
	Value MessageReplyPreview
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilMessageReplyPreview was set.
func (o OptNilMessageReplyPreview) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilMessageReplyPreview) Reset() {
	var v MessageReplyPreview
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilMessageReplyPreview) SetTo(v MessageReplyPreview) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilMessageReplyPreview) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilMessageReplyPreview) SetToNull() {
	o.Set = true
	o.Null = true
	var v MessageReplyPreview
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilMessageReplyPreview) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilMessageReplyPreview) Get() (v MessageReplyPreview, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilMessageReplyPreview) Or(d MessageReplyPreview) MessageReplyPreview {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilURI returns new OptNilURI with value set to v.
func NewOptNilURI(v url.URL) OptNilURI {
	return OptNilURI{
		Value: v,
		Set:   true,
	}
}

// OptNilURI is optional nullable url.URL.
type OptNilURI struct {
	Value url.URL
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilURI was set.
func (o OptNilURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilURI) SetTo(v url.URL) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilURI) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilURI) SetToNull() {
	o.Set = true
	o.Null = true
	var v url.URL
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilURI) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilURI) Get() (v url.URL, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Participant
type Participant struct {
	ParticipantType ParticipantType `json:"participantType"`
	// Opaque identifier of the participant, null for a BOT participant.
	UserID OptNilString `json:"userId"`
	// The read watermark model (PRD §9.5, §12.9). Null if this participant has not read any messages
	// yet. When multiple AGENT participants exist, a client should take the maximum `lastReadAt` across
	// them.
	LastReadAt NilDateTime `json:"lastReadAt"`
}

// GetParticipantType returns the value of ParticipantType.
func (s *Participant) GetParticipantType() ParticipantType {
	return s.ParticipantType
}

// GetUserID returns the value of UserID.
func (s *Participant) GetUserID() OptNilString {
	return s.UserID
}

// GetLastReadAt returns the value of LastReadAt.
func (s *Participant) GetLastReadAt() NilDateTime {
	return s.LastReadAt
}

// SetParticipantType sets the value of ParticipantType.
func (s *Participant) SetParticipantType(val ParticipantType) {
	s.ParticipantType = val
}

// SetUserID sets the value of UserID.
func (s *Participant) SetUserID(val OptNilString) {
	s.UserID = val
}

// SetLastReadAt sets the value of LastReadAt.
func (s *Participant) SetLastReadAt(val NilDateTime) {
	s.LastReadAt = val
}

// Who a session participant is. Distinct from SenderType — a participant has no SYSTEM value.
// Ref: #/components/schemas/ParticipantType
type ParticipantType string

const (
	ParticipantTypeCUSTOMER ParticipantType = "CUSTOMER"
	ParticipantTypeAGENT    ParticipantType = "AGENT"
	ParticipantTypeBOT      ParticipantType = "BOT"
)

// AllValues returns all ParticipantType values.
func (ParticipantType) AllValues() []ParticipantType {
	return []ParticipantType{
		ParticipantTypeCUSTOMER,
		ParticipantTypeAGENT,
		ParticipantTypeBOT,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ParticipantType) MarshalText() ([]byte, error) {
	switch s {
	case ParticipantTypeCUSTOMER:
		return []byte(s), nil
	case ParticipantTypeAGENT:
		return []byte(s), nil
	case ParticipantTypeBOT:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ParticipantType) UnmarshalText(data []byte) error {
	switch ParticipantType(data) {
	case ParticipantTypeCUSTOMER:
		*s = ParticipantTypeCUSTOMER
		return nil
	case ParticipantTypeAGENT:
		*s = ParticipantTypeAGENT
		return nil
	case ParticipantTypeBOT:
		*s = ParticipantTypeBOT
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Enriched participant profile, generalized from v1's assignedAgent/customer shapes.
// Ref: #/components/schemas/Profile
type Profile struct {
	// Correlation key. `presence.update` frames and `readWatermarks` are both keyed by this, so without it
	// neither can be bound to a person.
	ParticipantID string    `json:"participantId"`
	DisplayName   string    `json:"displayName"`
	Email         NilString `json:"email"`
	AvatarURL     NilURI    `json:"avatarUrl"`
}

// GetParticipantID returns the value of ParticipantID.
func (s *Profile) GetParticipantID() string {
	return s.ParticipantID
}

// GetDisplayName returns the value of DisplayName.
func (s *Profile) GetDisplayName() string {
	return s.DisplayName
}

// GetEmail returns the value of Email.
func (s *Profile) GetEmail() NilString {
	return s.Email
}

// GetAvatarURL returns the value of AvatarURL.
func (s *Profile) GetAvatarURL() NilURI {
	return s.AvatarURL
}

// SetParticipantID sets the value of ParticipantID.
func (s *Profile) SetParticipantID(val string) {
	s.ParticipantID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Profile) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetEmail sets the value of Email.
func (s *Profile) SetEmail(val NilString) {
	s.Email = val
}

// SetAvatarURL sets the value of AvatarURL.
func (s *Profile) SetAvatarURL(val NilURI) {
	s.AvatarURL = val
}

type PublishableKey struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *PublishableKey) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *PublishableKey) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *PublishableKey) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *PublishableKey) SetRoles(val []string) {
	s.Roles = val
}

type SecretKey struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *SecretKey) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *SecretKey) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *SecretKey) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *SecretKey) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/SenderType
type SenderType string

const (
	SenderTypeCUSTOMER SenderType = "CUSTOMER"
	SenderTypeAGENT    SenderType = "AGENT"
	SenderTypeBOT      SenderType = "BOT"
	SenderTypeSYSTEM   SenderType = "SYSTEM"
)

// AllValues returns all SenderType values.
func (SenderType) AllValues() []SenderType {
	return []SenderType{
		SenderTypeCUSTOMER,
		SenderTypeAGENT,
		SenderTypeBOT,
		SenderTypeSYSTEM,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SenderType) MarshalText() ([]byte, error) {
	switch s {
	case SenderTypeCUSTOMER:
		return []byte(s), nil
	case SenderTypeAGENT:
		return []byte(s), nil
	case SenderTypeBOT:
		return []byte(s), nil
	case SenderTypeSYSTEM:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SenderType) UnmarshalText(data []byte) error {
	switch SenderType(data) {
	case SenderTypeCUSTOMER:
		*s = SenderTypeCUSTOMER
		return nil
	case SenderTypeAGENT:
		*s = SenderTypeAGENT
		return nil
	case SenderTypeBOT:
		*s = SenderTypeBOT
		return nil
	case SenderTypeSYSTEM:
		*s = SenderTypeSYSTEM
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SessionFull
type SessionFull struct {
	Session      ChatSession   `json:"session"`
	Participants []Participant `json:"participants"`
	// Most recent page, ascending chronological order (oldest first).
	Messages []ChatMessage `json:"messages"`
	// Whether older messages exist beyond this page. Page further back with
	// `GET /sessions/{sessionId}/messages`.
	HasMore bool `json:"hasMore"`
}

// GetSession returns the value of Session.
func (s *SessionFull) GetSession() ChatSession {
	return s.Session
}

// GetParticipants returns the value of Participants.
func (s *SessionFull) GetParticipants() []Participant {
	return s.Participants
}

// GetMessages returns the value of Messages.
func (s *SessionFull) GetMessages() []ChatMessage {
	return s.Messages
}

// GetHasMore returns the value of HasMore.
func (s *SessionFull) GetHasMore() bool {
	return s.HasMore
}

// SetSession sets the value of Session.
func (s *SessionFull) SetSession(val ChatSession) {
	s.Session = val
}

// SetParticipants sets the value of Participants.
func (s *SessionFull) SetParticipants(val []Participant) {
	s.Participants = val
}

// SetMessages sets the value of Messages.
func (s *SessionFull) SetMessages(val []ChatMessage) {
	s.Messages = val
}

// SetHasMore sets the value of HasMore.
func (s *SessionFull) SetHasMore(val bool) {
	s.HasMore = val
}

func (*SessionFull) getSessionFullRes() {}

// Ref: #/components/schemas/SessionSummaryPage
type SessionSummaryPage struct {
	Sessions []ChatSessionSummary `json:"sessions"`
	HasMore  bool                 `json:"hasMore"`
}

// GetSessions returns the value of Sessions.
func (s *SessionSummaryPage) GetSessions() []ChatSessionSummary {
	return s.Sessions
}

// GetHasMore returns the value of HasMore.
func (s *SessionSummaryPage) GetHasMore() bool {
	return s.HasMore
}

// SetSessions sets the value of Sessions.
func (s *SessionSummaryPage) SetSessions(val []ChatSessionSummary) {
	s.Sessions = val
}

// SetHasMore sets the value of HasMore.
func (s *SessionSummaryPage) SetHasMore(val bool) {
	s.HasMore = val
}

func (*SessionSummaryPage) listSessionsRes() {}

// A linked CRM/support ticket (see the `ticket.linked` WS frame and webhook).
// Ref: #/components/schemas/Ticket
type Ticket struct {
	// Opaque ticket identifier.
	ID  string    `json:"id"`
	URL OptNilURI `json:"url"`
}

// GetID returns the value of ID.
func (s *Ticket) GetID() string {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Ticket) GetURL() OptNilURI {
	return s.URL
}

// SetID sets the value of ID.
func (s *Ticket) SetID(val string) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Ticket) SetURL(val OptNilURI) {
	s.URL = val
}

// TooManyRequestsHeaders wraps Error with response headers.
type TooManyRequestsHeaders struct {
	RateLimitLimit     OptInt
	RateLimitRemaining OptInt
	RateLimitReset     OptInt
	RetryAfter         OptInt
	XRequestID         OptString
	Response           Error
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *TooManyRequestsHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *TooManyRequestsHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *TooManyRequestsHeaders) GetRateLimitReset() OptInt {
	return s.RateLimitReset
}

// GetRetryAfter returns the value of RetryAfter.
func (s *TooManyRequestsHeaders) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetXRequestID returns the value of XRequestID.
func (s *TooManyRequestsHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *TooManyRequestsHeaders) GetResponse() Error {
	return s.Response
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *TooManyRequestsHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *TooManyRequestsHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *TooManyRequestsHeaders) SetRateLimitReset(val OptInt) {
	s.RateLimitReset = val
}

// SetRetryAfter sets the value of RetryAfter.
func (s *TooManyRequestsHeaders) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetXRequestID sets the value of XRequestID.
func (s *TooManyRequestsHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *TooManyRequestsHeaders) SetResponse(val Error) {
	s.Response = val
}

func (*TooManyRequestsHeaders) closeSessionRes()            {}
func (*TooManyRequestsHeaders) createSessionRes()           {}
func (*TooManyRequestsHeaders) getSessionFullRes()          {}
func (*TooManyRequestsHeaders) listSessionMessagesRes()     {}
func (*TooManyRequestsHeaders) listSessionsRes()            {}
func (*TooManyRequestsHeaders) mintTokenRes()               {}
func (*TooManyRequestsHeaders) reopenSessionRes()           {}
func (*TooManyRequestsHeaders) uploadSessionAttachmentRes() {}

// UnauthorizedHeaders wraps Error with response headers.
type UnauthorizedHeaders struct {
	XRequestID OptString
	Response   Error
}

// GetXRequestID returns the value of XRequestID.
func (s *UnauthorizedHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthorizedHeaders) GetResponse() Error {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *UnauthorizedHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthorizedHeaders) SetResponse(val Error) {
	s.Response = val
}

func (*UnauthorizedHeaders) closeSessionRes()            {}
func (*UnauthorizedHeaders) createSessionRes()           {}
func (*UnauthorizedHeaders) getSessionFullRes()          {}
func (*UnauthorizedHeaders) listSessionMessagesRes()     {}
func (*UnauthorizedHeaders) listSessionsRes()            {}
func (*UnauthorizedHeaders) mintTokenRes()               {}
func (*UnauthorizedHeaders) reopenSessionRes()           {}
func (*UnauthorizedHeaders) uploadSessionAttachmentRes() {}

type UploadSessionAttachmentReq struct {
	// The file to upload. Accepted categories map to `mediaType` in the response: images, video, audio,
	// and common document formats (pdf, doc/docx, xls/xlsx, csv, txt, zip). Exact allow-list and max size
	// are server-enforced and not fixed by this spec.
	File string `json:"file"`
}

// GetFile returns the value of File.
func (s *UploadSessionAttachmentReq) GetFile() string {
	return s.File
}

// SetFile sets the value of File.
func (s *UploadSessionAttachmentReq) SetFile(val string) {
	s.File = val
}

type UploadSessionAttachmentRequestEntityTooLarge Error

func (*UploadSessionAttachmentRequestEntityTooLarge) uploadSessionAttachmentRes() {}

type UploadSessionAttachmentUnsupportedMediaType Error

func (*UploadSessionAttachmentUnsupportedMediaType) uploadSessionAttachmentRes() {}

// Ref: #/components/schemas/WebhookMessageCreatedEvent
type WebhookMessageCreatedEvent struct {
	ID        string      `json:"id"`
	Type      string      `json:"type"`
	CreatedAt time.Time   `json:"createdAt"`
	TenantID  string      `json:"tenantId"`
	Data      ChatMessage `json:"data"`
}

// GetID returns the value of ID.
func (s *WebhookMessageCreatedEvent) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *WebhookMessageCreatedEvent) GetType() string {
	return s.Type
}

// GetCreatedAt returns the value of CreatedAt.
func (s *WebhookMessageCreatedEvent) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetTenantID returns the value of TenantID.
func (s *WebhookMessageCreatedEvent) GetTenantID() string {
	return s.TenantID
}

// GetData returns the value of Data.
func (s *WebhookMessageCreatedEvent) GetData() ChatMessage {
	return s.Data
}

// SetID sets the value of ID.
func (s *WebhookMessageCreatedEvent) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *WebhookMessageCreatedEvent) SetType(val string) {
	s.Type = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *WebhookMessageCreatedEvent) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetTenantID sets the value of TenantID.
func (s *WebhookMessageCreatedEvent) SetTenantID(val string) {
	s.TenantID = val
}

// SetData sets the value of Data.
func (s *WebhookMessageCreatedEvent) SetData(val ChatMessage) {
	s.Data = val
}

// WebhookMessageCreatedOK is response for WebhookMessageCreated operation.
type WebhookMessageCreatedOK struct{}

// Ref: #/components/schemas/WebhookSessionClosedEvent
type WebhookSessionClosedEvent struct {
	ID        string                        `json:"id"`
	Type      string                        `json:"type"`
	CreatedAt time.Time                     `json:"createdAt"`
	TenantID  string                        `json:"tenantId"`
	Data      WebhookSessionClosedEventData `json:"data"`
}

// GetID returns the value of ID.
func (s *WebhookSessionClosedEvent) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *WebhookSessionClosedEvent) GetType() string {
	return s.Type
}

// GetCreatedAt returns the value of CreatedAt.
func (s *WebhookSessionClosedEvent) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetTenantID returns the value of TenantID.
func (s *WebhookSessionClosedEvent) GetTenantID() string {
	return s.TenantID
}

// GetData returns the value of Data.
func (s *WebhookSessionClosedEvent) GetData() WebhookSessionClosedEventData {
	return s.Data
}

// SetID sets the value of ID.
func (s *WebhookSessionClosedEvent) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *WebhookSessionClosedEvent) SetType(val string) {
	s.Type = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *WebhookSessionClosedEvent) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetTenantID sets the value of TenantID.
func (s *WebhookSessionClosedEvent) SetTenantID(val string) {
	s.TenantID = val
}

// SetData sets the value of Data.
func (s *WebhookSessionClosedEvent) SetData(val WebhookSessionClosedEventData) {
	s.Data = val
}

type WebhookSessionClosedEventData struct {
	Session     ChatSession `json:"session"`
	CloseReason CloseReason `json:"closeReason"`
}

// GetSession returns the value of Session.
func (s *WebhookSessionClosedEventData) GetSession() ChatSession {
	return s.Session
}

// GetCloseReason returns the value of CloseReason.
func (s *WebhookSessionClosedEventData) GetCloseReason() CloseReason {
	return s.CloseReason
}

// SetSession sets the value of Session.
func (s *WebhookSessionClosedEventData) SetSession(val ChatSession) {
	s.Session = val
}

// SetCloseReason sets the value of CloseReason.
func (s *WebhookSessionClosedEventData) SetCloseReason(val CloseReason) {
	s.CloseReason = val
}

// WebhookSessionClosedOK is response for WebhookSessionClosed operation.
type WebhookSessionClosedOK struct{}

// Ref: #/components/schemas/WebhookSessionUpdatedEvent
type WebhookSessionUpdatedEvent struct {
	ID        string      `json:"id"`
	Type      string      `json:"type"`
	CreatedAt time.Time   `json:"createdAt"`
	TenantID  string      `json:"tenantId"`
	Data      ChatSession `json:"data"`
}

// GetID returns the value of ID.
func (s *WebhookSessionUpdatedEvent) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *WebhookSessionUpdatedEvent) GetType() string {
	return s.Type
}

// GetCreatedAt returns the value of CreatedAt.
func (s *WebhookSessionUpdatedEvent) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetTenantID returns the value of TenantID.
func (s *WebhookSessionUpdatedEvent) GetTenantID() string {
	return s.TenantID
}

// GetData returns the value of Data.
func (s *WebhookSessionUpdatedEvent) GetData() ChatSession {
	return s.Data
}

// SetID sets the value of ID.
func (s *WebhookSessionUpdatedEvent) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *WebhookSessionUpdatedEvent) SetType(val string) {
	s.Type = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *WebhookSessionUpdatedEvent) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetTenantID sets the value of TenantID.
func (s *WebhookSessionUpdatedEvent) SetTenantID(val string) {
	s.TenantID = val
}

// SetData sets the value of Data.
func (s *WebhookSessionUpdatedEvent) SetData(val ChatSession) {
	s.Data = val
}

// WebhookSessionUpdatedOK is response for WebhookSessionUpdated operation.
type WebhookSessionUpdatedOK struct{}

// Ref: #/components/schemas/WebhookTicketLinkedEvent
type WebhookTicketLinkedEvent struct {
	ID        string                       `json:"id"`
	Type      string                       `json:"type"`
	CreatedAt time.Time                    `json:"createdAt"`
	TenantID  string                       `json:"tenantId"`
	Data      WebhookTicketLinkedEventData `json:"data"`
}

// GetID returns the value of ID.
func (s *WebhookTicketLinkedEvent) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *WebhookTicketLinkedEvent) GetType() string {
	return s.Type
}

// GetCreatedAt returns the value of CreatedAt.
func (s *WebhookTicketLinkedEvent) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetTenantID returns the value of TenantID.
func (s *WebhookTicketLinkedEvent) GetTenantID() string {
	return s.TenantID
}

// GetData returns the value of Data.
func (s *WebhookTicketLinkedEvent) GetData() WebhookTicketLinkedEventData {
	return s.Data
}

// SetID sets the value of ID.
func (s *WebhookTicketLinkedEvent) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *WebhookTicketLinkedEvent) SetType(val string) {
	s.Type = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *WebhookTicketLinkedEvent) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetTenantID sets the value of TenantID.
func (s *WebhookTicketLinkedEvent) SetTenantID(val string) {
	s.TenantID = val
}

// SetData sets the value of Data.
func (s *WebhookTicketLinkedEvent) SetData(val WebhookTicketLinkedEventData) {
	s.Data = val
}

type WebhookTicketLinkedEventData struct {
	SessionID string `json:"sessionId"`
	Ticket    Ticket `json:"ticket"`
}

// GetSessionID returns the value of SessionID.
func (s *WebhookTicketLinkedEventData) GetSessionID() string {
	return s.SessionID
}

// GetTicket returns the value of Ticket.
func (s *WebhookTicketLinkedEventData) GetTicket() Ticket {
	return s.Ticket
}

// SetSessionID sets the value of SessionID.
func (s *WebhookTicketLinkedEventData) SetSessionID(val string) {
	s.SessionID = val
}

// SetTicket sets the value of Ticket.
func (s *WebhookTicketLinkedEventData) SetTicket(val Ticket) {
	s.Ticket = val
}

// WebhookTicketLinkedOK is response for WebhookTicketLinked operation.
type WebhookTicketLinkedOK struct{}
