#!/usr/bin/env python3
"""Emit the API base path, derived from the OpenAPI `servers` block, as source.

Neither ogen (Go) nor openapi-python-client bakes the `servers` URL into the
generated client: both take a base URL from the caller. That is exactly the
failure this repo already had once -- the spec used to say `{apiUrl}/v1`, a
path no route serves, and a generated client would have looked correct while
requesting nothing. So the base path is not left to a consumer's memory or to
prose in a README: it is derived from the spec at generation time and emitted
as a constant in both clients, and `check-drift.sh` fails if the spec's
`servers` block moves without the clients being regenerated.

This script is deliberately strict. Any `servers` shape it does not recognise
is an error, not a silently-degraded guess.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from ruamel.yaml import YAML

# The server URL must be exactly this variable followed by a literal path.
# `apiUrl` is `ChatClientConfig.apiUrl` (PRD 6.1): an origin, no path segment.
ORIGIN_VARIABLE = "apiUrl"


class SpecError(RuntimeError):
    pass


def base_path_from_spec(spec: dict) -> str:
    servers = spec.get("servers")
    if not isinstance(servers, list) or len(servers) != 1:
        raise SpecError(
            f"expected exactly one entry in `servers`, found "
            f"{0 if not isinstance(servers, list) else len(servers)}. "
            "Multiple servers would mean the clients need a server-selection "
            "story, which they do not have -- decide that before regenerating."
        )

    url = servers[0].get("url")
    if not isinstance(url, str):
        raise SpecError("servers[0].url is missing or is not a string")

    prefix = "{" + ORIGIN_VARIABLE + "}"
    if not url.startswith(prefix):
        raise SpecError(
            f"servers[0].url must start with {prefix!r}, got {url!r}. "
            "The clients join a caller-supplied origin to a fixed path; a URL "
            "shaped any other way needs a code change here, not a guess."
        )

    variables = servers[0].get("variables") or {}
    if ORIGIN_VARIABLE not in variables:
        raise SpecError(
            f"servers[0].url references {prefix} but declares no "
            f"`variables.{ORIGIN_VARIABLE}`"
        )

    base_path = url[len(prefix) :]
    if not base_path.startswith("/"):
        raise SpecError(f"base path must start with '/', got {base_path!r}")
    if base_path.endswith("/"):
        raise SpecError(f"base path must not end with '/', got {base_path!r}")
    if re.search(r"[{}]", base_path):
        raise SpecError(
            f"base path {base_path!r} contains a server variable. Only "
            f"{prefix} is supported; anything else needs templating the "
            "clients do not do."
        )
    return base_path


# The first line matches Go's ^// Code generated .* DO NOT EDIT\.$ convention,
# which gofmt, go vet and code-review tooling all key off. It has to stay on
# one line to be recognised.
GO_TEMPLATE = '''// Code generated by clients/scripts/emit_base_path.py from openapi/chat-api.yaml. DO NOT EDIT.

package chatapi

import "strings"

// BasePath is the path every route on chat-service is mounted under, taken
// from the spec's `servers` block. ogen does not bake it into the generated
// client -- NewClient takes a full server URL -- so joining it is on the
// caller. Use ResolveBaseURL rather than concatenating by hand.
const BasePath = {base_path}

// ResolveBaseURL turns a chat-service origin (scheme + host, the value a
// consumer configures as apiUrl) into the server URL NewClient expects.
//
//	c, err := chatapi.NewClient(chatapi.ResolveBaseURL("https://chat.example.com"), sec)
//
// A trailing slash on the origin is tolerated. A path segment on the origin
// is not stripped: apiUrl is documented as origin-only, and silently
// discarding a path a caller deliberately supplied would hide their mistake
// rather than surface it.
func ResolveBaseURL(apiURL string) string {{
	return strings.TrimRight(apiURL, "/") + BasePath
}}
'''

PY_TEMPLATE = '''"""Code generated by clients/scripts/emit_base_path.py from openapi/chat-api.yaml. DO NOT EDIT."""

BASE_PATH = {base_path}
"""Path every route on chat-service is mounted under, taken from the spec's
`servers` block. openapi-python-client does not bake it into the generated
client -- ``Client`` takes ``base_url`` -- so joining it is on the caller.
Use :func:`resolve_base_url` rather than concatenating by hand.
"""


def resolve_base_url(api_url: str) -> str:
    """Turn a chat-service origin into the ``base_url`` ``Client`` expects.

        client = AuthenticatedClient(
            base_url=resolve_base_url("https://chat.example.com"), token=...
        )

    A trailing slash on the origin is tolerated. A path segment on the origin
    is not stripped: ``apiUrl`` is documented as origin-only, and silently
    discarding a path a caller deliberately supplied would hide their mistake
    rather than surface it.
    """
    return api_url.rstrip("/") + BASE_PATH
'''


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(
            "usage: emit_base_path.py <spec.yaml> <out.go> <out.py>",
            file=sys.stderr,
        )
        return 2

    spec_path, go_out, py_out = (Path(p) for p in argv[1:])
    spec = YAML(typ="safe").load(spec_path.read_text(encoding="utf-8"))

    try:
        base_path = base_path_from_spec(spec)
    except SpecError as exc:
        print(f"error: {spec_path}: {exc}", file=sys.stderr)
        return 1

    # A Go string literal and a Python string literal are both satisfied by a
    # double-quoted, backslash-escaped form for the character set a URL path
    # can hold.
    literal = '"' + base_path.replace("\\", "\\\\").replace('"', '\\"') + '"'

    go_out.write_text(GO_TEMPLATE.format(base_path=literal), encoding="utf-8")
    py_out.write_text(PY_TEMPLATE.format(base_path=literal), encoding="utf-8")
    print(f"base path {base_path} -> {go_out}, {py_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
