#!/usr/bin/env bash
#
# Rewrite clients/generated.lock from the current tree. Called by generate.sh;
# there is no reason to run it by hand -- doing so would record whatever is on
# disk as correct, which is precisely what the lock exists to disprove.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
clients_dir="$(dirname "$here")"
repo_root="$(dirname "$clients_dir")"

# shellcheck source=lib.sh
source "$here/lib.sh"
# shellcheck source=versions.env
source "$here/versions.env"

{
  cat <<'HEADER'
# Generated by clients/scripts/generate.sh. DO NOT EDIT BY HAND.
#
# What each line is for:
#   spec       the spec the committed clients were generated from. If the spec
#              changes and nobody regenerates, check-drift.sh fails on this.
#   generator  the pinned toolchain. Output is byte-compared, so a version
#              change is a content change.
#   tree       a digest over the contents AND the layout of each generated
#              package, so a hand-edit of generated code fails too.
HEADER
  printf 'spec\t%s\topenapi/chat-api.yaml\n' \
    "$(sha256_file "$repo_root/openapi/chat-api.yaml")"
  printf 'generator\t%s\togen\n' "$OGEN_VERSION"
  printf 'generator\t%s\topenapi-python-client\n' "$OPENAPI_PYTHON_CLIENT_VERSION"
  printf 'generator\t%s\truff\n' "$RUFF_VERSION"
  printf 'tree\t%s\tgo/chatapi\n' "$(tree_sha256 "$clients_dir" go/chatapi)"
  printf 'tree\t%s\tpython/dhaam_ccrm_chat\n' \
    "$(tree_sha256 "$clients_dir" python/dhaam_ccrm_chat)"
} > "$clients_dir/generated.lock"

echo "wrote $clients_dir/generated.lock"
